Repository Aiven-Open/klaw, pull requests merged in 2022-11, with the labels that each got.

#200 docs(coral): Add base for frontend testing approach in coral docs.
  coral/docs/frontend-testing.md
Labels: Frontend

#201 refactor(coral): Enable custom setup and teardown in React tests.
  coral/jest.config.ts
  coral/src/app/features/login/LoginForm.test.tsx
  coral/src/app/pages/Hello.test.tsx
  coral/src/app/pages/Login.test.tsx
  coral/src/app/pages/index.test.tsx
Labels: Frontend

#202 feat(coral): build topics list view
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/features/topics/BrowseTopics.test.tsx
  coral/src/app/features/topics/BrowseTopics.tsx
  coral/src/app/features/topics/components/TopicCard.module.css
  coral/src/app/features/topics/components/TopicCard.test.tsx
  coral/src/app/features/topics/components/TopicCard.tsx
  coral/src/app/features/topics/components/TopicList.test.tsx
  coral/src/app/features/topics/components/TopicList.tsx
  coral/src/app/features/topics/hooks/useGetTopics.test.tsx
  coral/src/app/features/topics/hooks/useGetTopics.ts
  coral/src/app/features/topics/utils/create-topic-overview-link.ts
  coral/src/app/features/topics/utils/create-topic-overview-links.test.ts
  coral/src/app/layout/SideNavigation.tsx
  coral/src/app/pages/Hello.test.tsx
  coral/src/app/pages/Hello.tsx
  coral/src/app/pages/topics/index.test.tsx
  coral/src/app/pages/topics/index.tsx
  coral/src/app/router.tsx
  coral/src/domain/topics/index.ts
  coral/src/domain/topics/topic-test-helper.test.ts
  coral/src/domain/topics/topic-test-helper.ts
  coral/src/domain/topics/topic-transformer.test.ts
  coral/src/domain/topics/topic-transformer.ts
  coral/src/domain/topics/topics-api.msw.ts
  coral/src/domain/topics/topics-api.ts
  coral/src/domain/topics/topics-types.ts
  coral/src/services/test-utils/render-helpers.tsx
  coral/vite.config.ts
Labels: Frontend

#203 Advanced topic configuration in topic requests
  cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/ClusterTopicRequest.java
  cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/ApacheKafkaTopicService.java
  core/src/main/java/io/aiven/klaw/controller/TopicController.java
  core/src/main/java/io/aiven/klaw/dao/TopicRequest.java
  core/src/main/java/io/aiven/klaw/error/KlawExceptionHandler.java
  core/src/main/java/io/aiven/klaw/model/TopicConfigEntry.java
  core/src/main/java/io/aiven/klaw/model/TopicConfiguration.java
  core/src/main/java/io/aiven/klaw/model/TopicConfigurationRequest.java
  core/src/main/java/io/aiven/klaw/model/TopicRequestModel.java
  core/src/main/java/io/aiven/klaw/model/cluster/ClusterTopicRequest.java
  core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  core/src/main/java/io/aiven/klaw/service/ServerConfigService.java
  core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
  core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
  core/src/main/java/io/aiven/klaw/validation/TopicRequestValidator.java
  core/src/main/java/io/aiven/klaw/validation/TopicRequestValidatorImpl.java
  core/src/main/resources/db/changelog/changelog.yaml
  core/src/main/resources/static/js/requestTopics.js
  core/src/main/resources/templates/execTopics.html
  core/src/main/resources/templates/myTopicRequests.html
  core/src/main/resources/templates/requestTopics.html
  core/src/test/java/io/aiven/klaw/MockMethods.java
  core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
  core/src/test/java/io/aiven/klaw/UtilMethods.java
  core/src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java
  core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
Labels: Backend

#211 misc: Add OpenAPI specification to /getTopics endpoint
  openapi.yaml
Labels: Frontend

#212 feat(coral): Enable pagination for topic list view
  coral/src/app/components/Pagination.module.css
  coral/src/app/components/Pagination.test.tsx
  coral/src/app/components/Pagination.tsx
  coral/src/app/features/topics/BrowseTopics.test.tsx
  coral/src/app/features/topics/BrowseTopics.tsx
  coral/src/app/features/topics/components/TopicCard.test.tsx
  coral/src/app/features/topics/components/TopicList.test.tsx
  coral/src/app/features/topics/components/TopicList.tsx
  coral/src/app/features/topics/hooks/useGetTopics.test.tsx
  coral/src/app/features/topics/hooks/useGetTopics.ts
  coral/src/app/pages/index.tsx
  coral/src/app/pages/topics/index.test.tsx
  coral/src/domain/topics/topic-test-helper.test.ts
  coral/src/domain/topics/topic-test-helper.ts
  coral/src/domain/topics/topic-transformer.test.ts
  coral/src/domain/topics/topic-transformer.ts
  coral/src/domain/topics/topics-api.msw.ts
  coral/src/domain/topics/topics-api.ts
  coral/src/domain/topics/topics-types.ts
Labels: Frontend

#215 feat(coral): Enable running Coral against remote API over HTTPS [#214]
  .gitignore
  coral/README.md
  coral/docs/development-with-remote-api.md
  coral/vite.config.ts
Labels: Frontend

#218 feat(coral): enable filtering for topics view (#189)
  coral/src/app/features/topics/BrowseTopics.test.tsx
  coral/src/app/features/topics/BrowseTopics.tsx
  coral/src/app/features/topics/components/list/TopicCard.module.css
  coral/src/app/features/topics/components/list/TopicCard.test.tsx
  coral/src/app/features/topics/components/list/TopicCard.tsx
  coral/src/app/features/topics/components/list/TopicList.test.tsx
  coral/src/app/features/topics/components/list/TopicList.tsx
  coral/src/app/features/topics/components/select-env/SelectEnv.test.tsx
  coral/src/app/features/topics/components/select-env/SelectEnv.tsx
  coral/src/app/features/topics/components/select-team/SelectTeam.test.tsx
  coral/src/app/features/topics/components/select-team/SelectTeam.tsx
  coral/src/app/features/topics/hooks/env/useGetEnvs.test.tsx
  coral/src/app/features/topics/hooks/env/useGetEnvs.tsx
  coral/src/app/features/topics/hooks/list/useGetTopics.test.tsx
  coral/src/app/features/topics/hooks/list/useGetTopics.ts
  coral/src/app/features/topics/hooks/teams/useGetTeams.test.tsx
  coral/src/app/features/topics/hooks/teams/useGetTeams.tsx
  coral/src/app/features/topics/hooks/useGetTopics.test.tsx
  coral/src/app/pages/topics/index.test.tsx
  coral/src/domain/topics/index.ts
  coral/src/domain/topics/topic-test-helper.test.ts
  coral/src/domain/topics/topic-test-helper.ts
  coral/src/domain/topics/topic-transformer.test.ts
  coral/src/domain/topics/topic-transformer.ts
  coral/src/domain/topics/topics-api.msw.ts
  coral/src/domain/topics/topics-api.ts
  coral/src/domain/topics/topics-types.ts
Labels: Frontend

#191 Updating unit tests - AclControllerService, new test class for SyncAc…
  core/src/main/java/io/aiven/klaw/controller/AclController.java
  core/src/main/java/io/aiven/klaw/model/AclRequestsModel.java
  core/src/main/java/io/aiven/klaw/model/MailType.java
  core/src/main/java/io/aiven/klaw/service/AclControllerService.java
  core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  core/src/main/java/io/aiven/klaw/service/MailUtils.java
  core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java
  core/src/main/resources/static/js/myRequests.js
  core/src/main/resources/static/js/requestAcls.js
  core/src/main/resources/templates/synchronizeTopics.html
  core/src/test/java/io/aiven/klaw/UtilMethods.java
  core/src/test/java/io/aiven/klaw/controller/AclControllerTest.java
  core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
  core/src/test/java/io/aiven/klaw/service/AclSyncControllerServiceTest.java
  core/src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java
  core/src/test/java/io/aiven/klaw/service/TopicOverviewServiceTest.java
Labels: Backend

#237 refactor(coral): Move team api mocks.
  coral/src/app/features/topics/BrowseTopics.test.tsx
  coral/src/app/features/topics/hooks/teams/useGetTeams.test.tsx
  coral/src/app/features/topics/hooks/teams/useGetTeams.tsx
  coral/src/app/pages/topics/index.test.tsx
  coral/src/domain/team/team-api.msw.ts
  coral/src/domain/topic/topic-api.msw.ts
Labels: Housekeeping, Frontend

#233 feat: include environmentsGet operation to OpenAPI specification
  openapi.yaml
Labels: Frontend

#236 refactor(coral): Update directory structure
  coral/docs/directory-structure.md
  coral/src/app/features/browse-topics/BrowseTopics.test.tsx
  coral/src/app/features/browse-topics/BrowseTopics.tsx
  coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.test.tsx
  coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.tsx
  coral/src/app/features/browse-topics/components/select-team/SelectTeam.test.tsx
  coral/src/app/features/browse-topics/components/select-team/SelectTeam.tsx
  coral/src/app/features/browse-topics/components/topic-list/TopicCard.module.css
  coral/src/app/features/browse-topics/components/topic-list/TopicCard.test.tsx
  coral/src/app/features/browse-topics/components/topic-list/TopicCard.tsx
  coral/src/app/features/browse-topics/components/topic-list/TopicList.test.tsx
  coral/src/app/features/browse-topics/components/topic-list/TopicList.tsx
  coral/src/app/features/browse-topics/hooks/environment/useGetEnvironments.test.tsx
  coral/src/app/features/browse-topics/hooks/environment/useGetEnvironments.tsx
  coral/src/app/features/browse-topics/hooks/teams/useGetTeams.test.tsx
  coral/src/app/features/browse-topics/hooks/teams/useGetTeams.tsx
  coral/src/app/features/browse-topics/hooks/topic-list/useGetTopics.test.tsx
  coral/src/app/features/browse-topics/hooks/topic-list/useGetTopics.ts
  coral/src/app/features/browse-topics/utils/create-topic-overview-link.ts
  coral/src/app/features/browse-topics/utils/create-topic-overview-links.test.ts
  coral/src/app/features/login/Login.test.tsx
  coral/src/app/features/login/Login.tsx
  coral/src/app/features/login/components/LoginForm.test.tsx
  coral/src/app/features/login/components/LoginForm.tsx
  coral/src/app/features/login/hooks/useLoginUser.tsx
  coral/src/app/features/login/index.ts
  coral/src/app/pages/Login.tsx
  coral/src/app/pages/topics/index.tsx
  coral/src/app/router.tsx
  coral/src/domain/auth-user/auth-user-api.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/services/api.test.ts
  coral/src/services/api.ts
Labels: documentation, Frontend

#235 Move getUserName to one place
  core/src/main/java/io/aiven/klaw/helpers/UtilMethods.java
  core/src/main/java/io/aiven/klaw/service/AclControllerService.java
  core/src/main/java/io/aiven/klaw/service/AnalyticsControllerService.java
  core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
  core/src/main/java/io/aiven/klaw/service/MailUtils.java
  core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
Labels: Backend

#231 Use set to speed up contains operation
  core/src/main/java/io/aiven/klaw/service/AclControllerService.java
Labels: Backend

#239 feat(coral): add search functionality topics (#190)
  coral/src/app/components/Pagination.tsx
  coral/src/app/features/browse-topics/BrowseTopics.tsx
  coral/src/app/features/browse-topics/components/search/SearchTopics.test.tsx
  coral/src/app/features/browse-topics/components/search/SearchTopics.tsx
  coral/src/app/features/browse-topics/components/topic-list/TopicCard.module.css
  coral/src/app/features/browse-topics/components/topic-list/TopicCard.tsx
  coral/src/app/features/browse-topics/hooks/topic-list/useGetTopics.test.tsx
  coral/src/app/features/browse-topics/hooks/topic-list/useGetTopics.ts
  coral/src/app/main.module.css
  coral/src/app/main.tsx
  coral/src/domain/topic/topic-api.msw.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-queries.ts
Labels: Frontend
