Repository Aiven-Open/klaw, pull requests merged in 2023-03, with the labels that each got.

#732 feat(coral): Disable approve/reject buttons in approvals table while action is in progress
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
Labels: enhancement, Frontend

#731 feat(coral): use `request/statistics` endpoint in `ApprovalResourceTabs`
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/utils/request-status-helper.ts
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/requests/requests-api.ts
  coral/src/domain/requests/requests-transformers.test.ts
  coral/src/domain/requests/requests-transformers.ts
  coral/src/domain/requests/requests-types.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/schema-request/schema-request-types.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-types.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#737 fix(coral): fix endpoint for declining schema requests
  coral/src/domain/schema-request/schema-request-api.ts
Labels: Frontend

#745 fix(coral): Min-width in approvals table fits content
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/components/ApprovalsLayout.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
Labels: Frontend

#747 feat(coral): Add schema version to details modal for approvals
  coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.tsx
Labels: Frontend

#749 fix(coral): Change redirect url create workflows.
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/domain/requests/requests-types.ts
Labels: bug, Frontend

#752 fix(coral): Errors should be shown in alerts of type error
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/components/ApprovalsLayout.test.tsx
  coral/src/app/features/approvals/components/ApprovalsLayout.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: Frontend

#754 feat(coral): Add request types in approval tables
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/schemas/hooks/useTableFilters.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/app/features/approvals/topics/hooks/useTableFilters.test.tsx
  coral/src/app/features/approvals/utils/request-operation-type-helper.ts
  coral/src/app/features/approvals/utils/request-status-helper.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#756 fix(coral): More consistent copy
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.test.tsx
  coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.tsx
  coral/src/app/features/approvals/schemas/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/hooks/useTableFilters.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.test.tsx
  coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.tsx
  coral/src/app/features/topics/browse/components/topic-table/TopicTable.test.tsx
  coral/src/app/features/topics/browse/hooks/environment/useGetEnvironments.test.tsx
  coral/src/app/features/topics/browse/hooks/topic-list/useGetTopics.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/hooks/useFeatureFlag.test.ts
  coral/src/app/pages/topics/index.test.tsx
Labels: Frontend

#783 refactor(coral): Make ApprovalsLayout reusable as TableLayout
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/layouts/TableLayout.test.tsx
  coral/src/app/features/components/layouts/TableLayout.tsx
  coral/src/app/features/components/layouts/__snapshots__/TableLayout.test.tsx.snap
Labels: Housekeeping, Frontend

#784 fix(coral): Approvals: always make topic, env and status first columns
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
Labels: Housekeeping, Frontend

#789 feat(coral): Topic Requests: add API definition and types for `/getTopicRequests`
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-transformer.test.ts
  coral/src/domain/topic/topic-transformer.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#815 feat(coral): add API definition and types for `/getAclRequests`
  coral/src/domain/acl/acl-api.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#791 feat(coral): Fix hierarchy of `MainNavigation` items, render user's current team
  coral/src/app/layout/Layout.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/pages/index.test.tsx
  coral/src/app/pages/not-found/index.test.tsx
  coral/src/domain/auth-user/auth-user-api.ts
  coral/src/domain/auth-user/index.ts
  coral/src/domain/notification/notification-api.msw.ts
  coral/src/domain/notification/notification-api.test.ts
  coral/src/domain/notification/notification-api.ts
  coral/src/domain/notification/notification-transformer.test.ts
  coral/src/domain/notification/notification-transformer.ts
  coral/src/domain/notification/notification-types.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#816 feat(coral): Acl Requests: Add ACL requests page and table
  coral/src/app/features/requests/components/acls/AclRequests.test.tsx
  coral/src/app/features/requests/components/acls/AclRequests.tsx
  coral/src/app/features/requests/components/acls/components/AclRequestsTable.test.tsx
  coral/src/app/features/requests/components/acls/components/AclRequestsTable.tsx
  coral/src/app/pages/requests/acls/index.tsx
Labels: enhancement, Frontend

#804 chore(coral): Update packages
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/pages/topics/schema-request.test.tsx
Labels: dependencies, Frontend

#829 feat(coral): Acl Requests: Add pagination to AclRequests
  coral/src/app/features/requests/components/acls/AclRequests.test.tsx
  coral/src/app/features/requests/components/acls/AclRequests.tsx
Labels: enhancement, Frontend

#819 coral(feat): My Schema Requests - add API definition and types for `/getSchemaRequests`
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/domain/schema-request/index.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/schema-request/schema-request-transformer.test.ts
  coral/src/domain/schema-request/schema-request-transformer.ts
  coral/src/domain/schema-request/schema-request-types.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#834 feat(coral): Acl Requests: add search functionality
  coral/src/app/features/requests/components/acls/AclRequests.test.tsx
  coral/src/app/features/requests/components/acls/AclRequests.tsx
Labels: enhancement, Frontend

#831 coral(feat): Add table with my schema requests
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.tsx
  coral/src/app/features/requests/components/schemas/utils/mocked-schema-requests.ts
  coral/src/app/pages/requests/schemas/index.test.tsx
  coral/src/app/pages/requests/schemas/index.tsx
Labels: enhancement, Frontend

#832 coral(feat): Add pagination with functionality my-schema-requests
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
  coral/src/app/pages/requests/schemas/index.test.tsx
Labels: enhancement, Frontend

#849 refactor(coral): Rename url param for only showing my requests.
  coral/src/app/features/components/table-filters/MyRequestFilter.test.tsx
  coral/src/app/features/components/table-filters/MyRequestFilter.tsx
  coral/src/app/features/requests/components/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/components/topics/TopicRequests.tsx
Labels: Frontend

#845 coral(feat): My Schema Requests - add search functionality
  coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
Labels: enhancement, Frontend

#848 coral(feat): My Schema Requests - add filter functionality for environment and status
  coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/components/schemas/utils/mocked-api-responses.ts
  coral/src/app/pages/requests/schemas/index.test.tsx
Labels: enhancement, Frontend

#853 feat(coral): My Schema Requests - add Toggle for "Show only my requests"
  coral/src/app/features/components/layouts/TableLayout.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
Labels: enhancement, Frontend

#852 feat(coral): Acl Requests: add filter functionality (Environment, ACL type, Request type, Status)
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/requests/components/acls/AclRequests.test.tsx
  coral/src/app/features/requests/components/acls/AclRequests.tsx
  coral/src/app/features/requests/components/acls/components/AclRequestsTable.tsx
Labels: enhancement, Frontend

#855 refactor(coral) Make `RequestDetailsModal` reusable for my-requests.
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/RequestDetailsModal.test.tsx
  coral/src/app/features/components/RequestDetailsModal.tsx
Labels: Frontend

#859 feat(coral): My Schema Requests - add details view flow
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/components/SchemaRequestDetails.test.tsx
  coral/src/app/features/components/SchemaRequestDetails.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.tsx
Labels: enhancement, Frontend

#858 feat(coral): ACL requests: add Toggle for "Only my requests"
  coral/src/app/features/components/table-filters/MyRequestsFilter.test.tsx
  coral/src/app/features/components/table-filters/MyRequestsFilter.tsx
  coral/src/app/features/requests/components/acls/AclRequests.test.tsx
  coral/src/app/features/requests/components/acls/AclRequests.tsx
  coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/components/topics/TopicRequests.tsx
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/acl/acl-types.ts
Labels: enhancement, Frontend

#860 Fix: fix typo `SchemaRegstry[x]`
  core/src/main/java/io/aiven/klaw/controller/SchemaRegistryController.java
  core/src/main/java/io/aiven/klaw/service/RequestService.java
  core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
  core/src/test/java/io/aiven/klaw/controller/RequestControllerTest.java
  core/src/test/java/io/aiven/klaw/controller/SchemaRegistryControllerTest.java
  core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
  openapi.yaml
Labels: java, Backend

#870 feat(coral): Add shared delete request modal
  coral/src/app/features/requests/RequestResourcesTabs.test.tsx
  coral/src/app/features/requests/RequestsResourceTabs.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
  coral/src/app/features/requests/components/DeleteRequestDialog.test.tsx
  coral/src/app/features/requests/components/DeleteRequestDialog.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
  coral/src/app/features/requests/schemas/utils/mocked-api-responses.ts
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.test.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
  coral/src/app/pages/requests/acls/index.tsx
  coral/src/app/pages/requests/index.tsx
  coral/src/app/pages/requests/schemas/index.tsx
  coral/src/app/pages/requests/topics/index.tsx
Labels: enhancement, Frontend

#878 fix(coral): Approvals - Add missing refetch calls for tab tag number
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
Labels: bug, Frontend

#890 feat(coral): Update redirect routes after creating new requests
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: enhancement, Frontend

#877 feat(coral): My Schema Requests - add delete functionality
  coral/src/app/features/requests/components/DeleteRequestDialog.test.tsx
  coral/src/app/features/requests/components/DeleteRequestDialog.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
  coral/src/domain/schema-request/index.ts
  coral/src/domain/schema-request/schema-request-api.ts
Labels: enhancement, Frontend

#888 feat(coral): Add OperationTypeFilter
  coral/src/app/features/components/table-filters/AclTypeFilter.test.tsx
  coral/src/app/features/components/table-filters/OperationTypeFilter.test.tsx
  coral/src/app/features/components/table-filters/OperationTypeFilter.tsx
  coral/src/app/features/components/table-filters/StatusFilter.test.tsx
  coral/src/app/features/components/table-filters/TopicFilter.test.tsx
Labels: enhancement, Frontend

#884 docs(api): Add docs folder at root, add OpenAPI spec docs
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/generation_schema.png
  docs/openapi.md
Labels: documentation

#897 fix(coral): Wrap filter components in TableLayout
  coral/src/app/features/components/layouts/TableLayout.tsx
Labels: Frontend

#902 feat(coral): My Schema Requests - add filter functionality for Type
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
  coral/src/domain/schema-request/schema-request-api.ts
Labels: enhancement, Frontend

#905 fix(coral): Fix scrollbars showing inappropriately in Modals
  coral/src/app/components/Modal.module.css
Labels: bug, Frontend

#892 refactor(coral): Add "success" information "Request new..." workflows
  coral/src/app/components/Dialog.test.tsx
  coral/src/app/components/Dialog.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: Housekeeping, Frontend

#903 feat(coral): Add useTableFiltersValues hook
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/filters/AclTypeFilter.test.tsx
  coral/src/app/features/components/filters/AclTypeFilter.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.tsx
  coral/src/app/features/components/filters/MyRequestsFilter.test.tsx
  coral/src/app/features/components/filters/MyRequestsFilter.tsx
  coral/src/app/features/components/filters/OperationTypeFilter.test.tsx
  coral/src/app/features/components/filters/OperationTypeFilter.tsx
  coral/src/app/features/components/filters/StatusFilter.test.tsx
  coral/src/app/features/components/filters/StatusFilter.tsx
  coral/src/app/features/components/filters/TeamFilter.test.tsx
  coral/src/app/features/components/filters/TeamFilter.tsx
  coral/src/app/features/components/filters/TopicFilter.test.tsx
  coral/src/app/features/components/filters/TopicFilter.tsx
  coral/src/app/features/components/filters/useFiltersValues.test.tsx
  coral/src/app/features/components/filters/useFiltersValues.tsx
  coral/src/app/features/components/table-filters/MyRequestsFilter.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/schema-request/schema-request-api.ts
Labels: Housekeeping, Frontend

#922 refactor(coral): Align BrowseTopics with other tables
  coral/src/app/features/components/filters/TeamFilter.test.tsx
  coral/src/app/features/components/filters/TeamFilter.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/app/features/topics/browse/components/TopicTable.test.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
  coral/src/app/features/topics/browse/components/search/SearchTopics.test.tsx
  coral/src/app/features/topics/browse/components/search/SearchTopics.tsx
  coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.test.tsx
  coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.tsx
  coral/src/app/features/topics/browse/components/select-team-name/SelectTeamName.test.tsx
  coral/src/app/features/topics/browse/components/select-team-name/SelectTeamName.tsx
  coral/src/app/features/topics/browse/components/topic-table/TopicTable.module.css
  coral/src/app/features/topics/browse/components/topic-table/TopicTable.tsx
  coral/src/app/features/topics/browse/hooks/environment/useGetEnvironments.test.tsx
  coral/src/app/features/topics/browse/hooks/environment/useGetEnvironments.tsx
  coral/src/app/features/topics/browse/hooks/team-names/useGetTeamNames.test.tsx
  coral/src/app/features/topics/browse/hooks/team-names/useGetTeamNames.tsx
  coral/src/app/features/topics/browse/hooks/topic-list/useGetTopics.test.tsx
  coral/src/app/features/topics/browse/hooks/topic-list/useGetTopics.ts
  coral/src/app/pages/topics/index.test.tsx
  coral/src/domain/team/index.ts
  coral/src/domain/team/team-api.msw.ts
  coral/src/domain/team/team-types.ts
  coral/src/domain/topic/topic-queries.ts
Labels: Housekeeping, Frontend

#921 refactor(coral): Better error handling for ApiResonse[] cases
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/layouts/TableLayout.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/services/api.ts
  coral/src/services/mutation-utils.ts
Labels: Frontend

#926 feat(coral): Streamline naming and order for "My team's requests" views
  coral/src/app/features/approvals/utils/request-operation-type-helper.ts
  coral/src/app/features/components/filters/RequestTypeFilter.test.tsx
  coral/src/app/features/components/filters/RequestTypeFilter.tsx
  coral/src/app/features/components/filters/useFiltersValues.test.tsx
  coral/src/app/features/components/filters/useFiltersValues.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.test.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
  coral/src/domain/schema-request/schema-request-api.ts
Labels: Frontend

#937 chore(coral) Update aquarium 1.14
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/accessibility.module.css
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.tsx
  coral/src/app/features/topics/acl-request/fields/AclTypeField.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
Labels: Housekeeping, Frontend

#949 feat(coral): add ariaLabel prop to tables, pass a better label
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.test.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/app/features/topics/browse/components/TopicTable.test.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
Labels: enhancement, Frontend

#933 feat(api, coral): ACL approvals : Add filter by request type
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/controller/AclController.java
  core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
  core/src/main/java/io/aiven/klaw/service/AclControllerService.java
  core/src/test/java/io/aiven/klaw/controller/AclControllerTest.java
  core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
  openapi.yaml
Labels: enhancement, Backend, Frontend

#940 feat(coral): Use `search` param to filter by topics in data tables
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/components/filters/TopicFilter.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/topic/topic-api.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/controller/AclController.java
  core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
  core/src/main/java/io/aiven/klaw/service/AclControllerService.java
  core/src/test/java/io/aiven/klaw/controller/AclControllerTest.java
  core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
  openapi.yaml
Labels: enhancement, Backend, Frontend
