Repository Aiven-Open/klaw, pull requests merged in 2023-01, with the labels that each got.

#445 Teamname optional in topic request
  core/src/main/java/io/aiven/klaw/model/TopicRequestModel.java
  core/src/main/java/io/aiven/klaw/validation/TopicRequestValidatorImpl.java
  core/src/main/resources/static/js/requestTopics.js
  core/src/test/java/io/aiven/klaw/TopicRequestValidatorImplIT.java
  core/src/test/java/io/aiven/klaw/UtilMethods.java
Labels: Backend

#446 refactor(coral): Update topic request tests.
  coral/src/app/features/topics/request/TopicRequest.test.tsx
Labels: Housekeeping, Frontend

#449 fix(coral): Fix broken error message handling in some Form elements
  coral/src/app/accessibility.module.css
  coral/src/app/components/Form.test.tsx
  coral/src/app/components/Form.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
Labels: bug, Frontend

#442 refactor(coral): Refactor flaky BrowseTopics test
  .github/workflows/coral-pr-pipeline.yml
  coral/package.json
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/services/test-utils/mock-intersection-observer.ts
Labels: Housekeeping, Frontend

#444 refactor(coral): Make css class names consistent
  coral/README.md
  coral/src/app/features/topics/browse/components/topic-table/TopicTable.module.css
  coral/src/app/layout/main-navigation/MainNavigationLink.module.css
  coral/src/app/layout/main-navigation/MainNavigationSubmenuList.module.css
  coral/src/app/layout/skip-link/SkipLink.module.css
Labels: Housekeeping, Frontend

#461 refactor(coral) Add "start" as alias for "pnpm dev".
  coral/package.json
Labels: Housekeeping, Frontend

#486 coral(style): Add linting rule for lodash imports
  coral/.eslintrc.cjs
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/components/FileInput.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
Labels: Housekeeping, Frontend

#487 coral(fix): Fix Icon in PreviewBanner resizes with browser
  coral/src/app/components/PreviewBanner.tsx
Labels: Housekeeping, Frontend

#447 feat(coral): Build form for "Request new schema" with mocked data
  coral/src/app/components/FileInput.tsx
  coral/src/app/components/Form.test.tsx
  coral/src/app/components/Form.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/features/topics/schema-request/components/TopicSchema.test.tsx
  coral/src/app/features/topics/schema-request/components/TopicSchema.tsx
  coral/src/app/features/topics/schema-request/schemas/topic-schema-request-form.ts
  coral/src/app/features/topics/schema-request/utils/read-file.ts
  coral/src/app/hooks/useFeatureFlag.ts
  coral/src/app/pages/topics/schema-request.test.tsx
  coral/src/app/pages/topics/schema-request.tsx
  coral/src/app/router.tsx
  coral/src/domain/environment/environment-api.msw.ts
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/index.ts
  coral/src/domain/schema-request/index.ts
  coral/src/domain/schema-request/schema-request-api.msw.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/test-setup/mock-monaco-editor.tsx
  coral/vite.config.ts
Labels: enhancement, Frontend

#509 feat(coral): Add error handling in frontend
  coral/src/services/api.test.ts
  coral/src/services/api.ts
  coral/src/services/mutation-utils.ts
  coral/src/services/type-utils.ts
Labels: enhancement, Frontend

#504 feat(coral) Last adjustments "Request new schema" view
  coral/src/app/accessibility.module.css
  coral/src/app/components/FileInput.module.css
  coral/src/app/components/FileInput.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/features/topics/schema-request/components/TopicSchema.test.tsx
  coral/src/app/features/topics/schema-request/components/TopicSchema.tsx
  coral/src/app/features/topics/schema-request/schemas/topic-schema-request-form.ts
  coral/src/app/hooks/useFeatureFlag.ts
  coral/vite.config.ts
  core/src/main/resources/templates/requestSchema.html
Labels: enhancement, Frontend
