Repository Aiven-Open/klaw, pull requests merged in 2023-04, with the labels that each got.

#975 feat(coral): Topic approvals, Schema approvals : Add operation type filter approvals
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend

#979 refactor(coral): Update main navigation based on current design.
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
Labels: Frontend

#983 feat(coral): Routing and skeleton page All Connectors view
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/pages/connectors/index.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
Labels: enhancement, Frontend

#995 refactor(coral): Update concept of Environment in coral
  coral/src/domain/environment/environment-api.msw.ts
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/environment/index.ts
Labels: Frontend

#1008 refactor(coral): Remove teamname as filter option in apis
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/filters/TeamFilter.test.tsx
  coral/src/app/features/components/filters/TeamFilter.tsx
  coral/src/app/features/components/filters/useFiltersValues.test.tsx
  coral/src/app/features/components/filters/useFiltersValues.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/domain/team/index.ts
  coral/src/domain/team/team-api.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-test-helper.ts
  coral/src/services/api-helper.test.ts
  coral/src/services/api-helper.ts
Labels: Frontend

#1015 refactor(coral) Update EnvironmentFilter to handle multiple endpoints.
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/environment/environment-test-helper.test.ts
  coral/src/domain/environment/environment-test-helper.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/index.ts
Labels: Frontend

#1016 feat(coral): Approve connector request: Add `Connectors` tab content (`DataTable`, filters)
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.tsx
  coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.test.tsx
  coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.tsx
Labels: enhancement, Frontend

#1018 feat(coral): Add filter for Environment and search field.
  coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend

#1036 refactor(coral): Use API_PATHS map instead of hardcoded paths in `domain`
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/auth-user/auth-user-api.ts
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/requests/requests-api.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/team/team-api.ts
  coral/src/domain/topic/topic-api.test.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/services/api.test.ts
  coral/src/services/api.ts
Labels: Housekeeping, Frontend

#1045 fix(coral): Add controlled value for MultiSelect
  coral/src/app/components/Form.tsx
Labels: bug, Frontend

#1049 feat(coral): Add preview banners for connectors
  coral/src/app/pages/approvals/connectors/index.tsx
  coral/src/app/pages/connectors/index.tsx
  core/src/main/resources/templates/execConnectors.html
  core/src/main/resources/templates/kafkaConnectors.html
  core/src/main/resources/templates/myConnectorRequests.html
Labels: enhancement, Frontend

#1058 feat(coral): Add `connectors/request` route and stub component
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/pages/connectors/index.tsx
  coral/src/app/pages/connectors/request.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
Labels: enhancement, Frontend

#1057 feat(coral): Add createConnectorRequest in domain/connector, update API response to be `"application/json"`
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/connector-types.ts
  coral/src/domain/connector/index.ts
  coral/src/domain/topic/topic-api.test.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/controller/AclController.java
  core/src/main/java/io/aiven/klaw/controller/AclSyncController.java
  core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
  core/src/main/java/io/aiven/klaw/controller/KafkaConnectController.java
  core/src/main/java/io/aiven/klaw/controller/KafkaConnectSyncController.java
  core/src/main/java/io/aiven/klaw/controller/RolesPermissionsController.java
  core/src/main/java/io/aiven/klaw/controller/ServerConfigController.java
  core/src/main/java/io/aiven/klaw/controller/TopicController.java
  core/src/main/java/io/aiven/klaw/controller/TopicSyncController.java
  core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
  core/src/main/java/io/aiven/klaw/controller/UtilController.java
  core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
  openapi.yaml
Labels: enhancement, Frontend

#1047 refactor(coral): Update `Form` and its implementations
  coral/src/app/components/Form.test.tsx
  coral/src/app/components/Form.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/login/components/LoginForm.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/acl-request/schemas/topic-acl-request-producer.ts
  coral/src/app/features/topics/acl-request/schemas/topic-acl-request-shared-fields.ts
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
Labels: Housekeeping, Frontend

#1061 refactor(coral): Fix api mocks in tests
  coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/pages/requests/connectors/index.test.tsx
  coral/src/services/api-mocks/server.ts
Labels: bug, Frontend

#1072 refactor(coral): Add Icon as link indicator in tables
  coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
Labels: Frontend

#1081 fix(coral): Make `MultiSelect` controlled
  coral/src/app/components/Form.tsx
  coral/src/app/features/topics/acl-request/fields/IpOrPrincipalField.test.tsx
Labels: bug, Frontend

#1088 build(deps): Dependency updates in coral
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx
Labels: Frontend

#1086 fix(coral): Add handling for missing params in `Environment`
  coral/src/app/features/topics/request/schemas/topic-request-form.ts
  coral/src/domain/environment/environment-transformer.test.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/services/api.ts
Labels: bug, Frontend

#1092 feat(coral): Enable isMyRequest in "My team's Connector requests"
  coral/src/domain/connector/connector-api.ts
Labels: enhancement, Frontend

#1082 feat(coral): Add regex validation for topic request
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/request/form-schemas/topic-request-form.ts
  coral/src/app/features/topics/request/utils.test.ts
  coral/src/app/features/topics/request/utils.ts
  coral/src/domain/environment/environment-transformer.test.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/topic/topic-api.test.ts
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend
