Repository Aiven-Open/klaw, pull requests merged in 2023-02, with the labels that each got.

#517 feat(coral): add base for /getCreatedTopicRequests API
  coral/src/domain/topic/topic-api.msw.ts
  coral/src/domain/topic/topic-api.test.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-test-helper.ts
  coral/src/domain/topic/topic-transformer.test.ts
  coral/src/domain/topic/topic-transformer.ts
  coral/src/domain/topic/topic-types.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#525 fix(coral): Make consumergroup value -na- only for Aiven clusters
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
Labels: Frontend

#523 feat(coral): Add approval request counts to tabs
  coral/src/app/features/approvals/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/ApprovalResourceTabs.tsx
  coral/src/domain/notification/notification-api.msw.ts
  coral/src/domain/notification/notification-api.test.ts
  coral/src/domain/notification/notification-api.ts
  coral/src/domain/notification/notification-transformer.test.ts
  coral/src/domain/notification/notification-transformer.ts
  coral/src/domain/notification/notification-types.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#560 feat(coral): Add /getAclRequestsForApprover endpoint
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/acl/acl-types.ts
  coral/types/api.d.ts
  coral/types/utils.d.ts
  openapi.yaml
Labels: Frontend

#566 feat(coral): add `/execAclRequest` endpoint
  coral/src/domain/acl/acl-api.ts
  coral/src/services/api.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#571 refactor(coral): Add general mock for DS Icon component
  coral/jest.config.ts
  coral/src/app/components/FileInput.test.tsx
  coral/src/app/components/Pagination.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/components/search/SearchTopics.test.tsx
  coral/src/app/layout/Layout.test.tsx
  coral/src/app/layout/header/Header.test.tsx
  coral/src/app/layout/header/HeaderMenuLink.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigationLink.test.tsx
  coral/src/app/layout/main-navigation/MainNavigationSubmenuList.test.tsx
  coral/src/app/pages/topics/schema-request.test.tsx
  coral/test-setup/mock-ds-icon-component.tsx
Labels: Housekeeping, Frontend

#527 refactor(coral): Remove custom implementation for placeholder NativeSelect
  coral/src/app/components/ComplexNativeSelect.test.tsx
  coral/src/app/components/ComplexNativeSelect.tsx
  coral/src/app/components/Form.test.tsx
  coral/src/app/components/Form.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameField.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/schemas/topic-acl-request-shared-fields.ts
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: Housekeeping, Frontend

#565 feat(coral): Add temporary Modal component
  coral/src/app/components/Modal.module.css
  coral/src/app/components/Modal.test.tsx
  coral/src/app/components/Modal.tsx
Labels: Housekeeping, Frontend

#572 Env name size increment from 3 to 10
  core/src/main/java/io/aiven/klaw/model/EnvModel.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  core/src/main/resources/static/js/envs.js
  core/src/main/resources/static/js/modifyEnvs.js
  core/src/main/resources/templates/modifyEnv.html
  core/src/test/java/io/aiven/klaw/EnvsClustersTenantsControllerIT.java
  core/src/test/java/io/aiven/klaw/controller/UiConfigControllerTest.java
Labels: Backend

#576 chore(coral): Update @aivenio/aquarium -> 1.5.0
  coral/package.json
  coral/pnpm-lock.yaml
Labels: Frontend

#569 Refactor(coral): Add type helper Prettify
  coral/src/app/components/ComplexNativeSelect.tsx
  coral/src/app/components/FileInput.tsx
  coral/src/domain/acl/acl-types.ts
  coral/src/domain/schema-request/schema-request-types.ts
  coral/src/services/api.ts
  coral/types/utils.d.ts
Labels: Housekeeping, Frontend

#570 Add filter options to the getTopicRequestsForApprover endpoint
  core/src/main/java/io/aiven/klaw/controller/AclController.java
  core/src/main/java/io/aiven/klaw/controller/TopicController.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
  core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
  core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
  core/src/main/resources/swagger_spec.json
  core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
  core/src/test/java/io/aiven/klaw/UtilMethods.java
  core/src/test/java/io/aiven/klaw/controller/TopicControllerTest.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/AclRequestsIntegrationTest.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicIntegrationTest.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java
  core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
Labels: Backend

#567 feat(coral): add `/execAclRequestDecline` endpoint
  coral/src/domain/acl/acl-api.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#568 fix: Change way pre-commit hooks are handled for React
  .githooks/pre-commit
  Makefile
  coral/README.md
  coral/package.json
  coral/pnpm-lock.yaml
Labels: Backend, Frontend

#581 feat(coral): Add DataTable and Pagination for ACL approval page
  coral/src/app/features/approvals/SkeletonTable.tsx
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/acl/acl-transformer.ts
  coral/src/domain/acl/acl-types.ts
Labels: Frontend

#594 style(coral): Add a11y improvements for tables.
  coral/src/app/accessibility.module.css
Labels: Frontend

#593 feat(coral): Add approvals layout component
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
  coral/src/app/features/approvals/components/ApprovalsLayout.test.tsx
  coral/src/app/features/approvals/components/ApprovalsLayout.tsx
  coral/src/app/features/approvals/components/__snapshots__/ApprovalsLayout.test.tsx.snap
  coral/src/app/pages/approvals/index.tsx
Labels: Frontend

#610 feat(coral): add data table approve topics request UI only
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/domain/topic/index.ts
  coral/src/domain/topic/topic-types.ts
Labels: enhancement, Frontend

#611 feat(coral): Add RequestDetailsModal and RequestDeclineModal
  coral/src/app/components/Modal.module.css
  coral/src/app/components/Modal.test.tsx
  coral/src/app/components/Modal.tsx
  coral/src/app/features/approvals/components/RequestDetailsModal.test.tsx
  coral/src/app/features/approvals/components/RequestDetailsModal.tsx
  coral/src/app/features/approvals/components/RequestRejectModal.test.tsx
  coral/src/app/features/approvals/components/RequestRejectModal.tsx
  coral/src/app/layout/Layout.tsx
Labels: enhancement, Frontend

#624 feat(coral): use ApprovalsLayout for AclApprovals component
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/domain/acl/acl-api.ts
Labels: Frontend

#629 feat(coral): Add approve/reject ACL subcription request behaviour
  coral/src/app/components/Modal.module.css
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/components/DetailsModalContent.test.tsx
  coral/src/app/features/approvals/acls/components/DetailsModalContent.tsx
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#635 feat(coral): Add api definition and types for unified approve and decline
  coral/src/domain/requests.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#622 style(coral): Consistent font-sizes to console
  coral/src/app/layout/Layout.tsx
  coral/src/app/main.module.css
Labels: bug, Frontend

#646 feat(coral): Extend ApprovalLayout
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/components/ApprovalsLayout.test.tsx
  coral/src/app/features/approvals/components/ApprovalsLayout.tsx
Labels: Frontend

#644 feat(coral): Implement filtering behaviour in ACL Approval table
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.test.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.tsx
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/acl/acl-types.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#654 Update openapi definition and types in coral.
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/components/DetailsModalContent.test.tsx
  coral/src/app/features/approvals/acls/components/DetailsModalContent.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.test.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/acl-request/fields/AclTypeField.test.tsx
  coral/src/app/features/topics/acl-request/fields/AclTypeField.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/acl-request/schemas/topic-acl-request-consumer.ts
  coral/src/app/features/topics/acl-request/schemas/topic-acl-request-producer.ts
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/request/utils.test.ts
  coral/src/app/features/topics/request/utils.ts
  coral/src/domain/acl/acl-types.ts
  coral/src/domain/acl/index.ts
  coral/src/domain/requests.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/schema-request/schema-request-transformer.test.ts
  coral/src/domain/schema-request/schema-request-types.ts
  coral/src/domain/topic/index.ts
  coral/src/domain/topic/topic-api.msw.ts
  coral/src/domain/topic/topic-api.test.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-test-helper.ts
  coral/src/domain/topic/topic-transformer.test.ts
  coral/src/domain/topic/topic-types.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#663 feat(coral): ACL approvals table: add status column
  coral/src/app/features/approvals/acls/AclApprovals.tsx
Labels: enhancement, Frontend

#662 feat(coral): Connect schema approval table to endpoint
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
Labels: enhancement, Frontend

#681 feat(coral): Add getTeams endpoint, add shared SelectTeam component
  coral/src/app/features/components/table-filters/SelectTeam.test.tsx
  coral/src/app/features/components/table-filters/SelectTeam.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/app/features/topics/browse/components/select-team-name/SelectTeamName.test.tsx
  coral/src/app/features/topics/browse/components/select-team-name/SelectTeamName.tsx
  coral/src/app/features/topics/browse/hooks/team-names/useGetTeamNames.test.tsx
  coral/src/app/features/topics/browse/hooks/team-names/useGetTeamNames.tsx
  coral/src/app/features/topics/browse/hooks/teams/useGetTeams.tsx
  coral/src/domain/team/index.ts
  coral/src/domain/team/team-api.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: Frontend

#666 fix(coral): Do not allow approve/reject when requestStatus is not CREATED
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/components/RequestDetailsModal.test.tsx
  coral/src/app/features/approvals/components/RequestDetailsModal.tsx
Labels: Frontend

#669 feat(coral): Topic request approval: add View details modal
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/DetailsModalContent.test.tsx
  coral/src/app/features/approvals/topics/components/DetailsModalContent.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
Labels: enhancement, Frontend

#685 chore(coral): Bump aquarium version -> 1.8.0
  coral/package.json
  coral/pnpm-lock.yaml
Labels: Housekeeping, Frontend

#687 feat(coral): Add approveTopicRequest and rejectTopicRequest endpoints
  coral/src/domain/topic/topic-api.ts
  coral/types/api.d.ts
  openapi.yaml
Labels: enhancement, Frontend

#678 feat(coral): Topic request approval: Add filters
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/app/features/approvals/topics/hooks/useTableFilters.test.tsx
  coral/src/app/features/approvals/topics/hooks/useTableFilters.tsx
  coral/src/domain/topic/topic-api.test.ts
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend

#672 feat(coral): add detail view modal to schema request approvals
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.tsx
  coral/src/app/features/topics/schema-request/components/TopicSchema.tsx
Labels: enhancement, Frontend

#692 feat(coral) Add api definition/types/functions for approve/decline schema request
  coral/src/domain/requests.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/schema-request/schema-request-types.ts
  coral/src/domain/topic/topic-api.ts
Labels: Frontend

#694 feat(coral): Topic requests table: add approve / reject topic request actions
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend

#699 chore(coral): Update approve and reject ACL request endpoints
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/domain/acl/acl-api.ts
Labels: Housekeeping, Frontend

#710 fix(coral): Disabled reject buttons if approval is in progress
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
Labels: enhancement, Frontend

#713 refactor(coral): Disable Connectors approvals tab
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
Labels: Housekeeping, Frontend

#715 feat(coral): Add preview banners for Approvals
  coral/src/app/pages/approvals/acls/index.tsx
  coral/src/app/pages/approvals/schemas/index.tsx
  coral/src/app/pages/approvals/topics/index.tsx
  core/src/main/resources/templates/execAcls.html
  core/src/main/resources/templates/execSchemas.html
  core/src/main/resources/templates/execTopics.html
Labels: enhancement, Frontend

#712 fix(coral): Approvals: replace all instances of "reject" by "decline"
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/components/RequestDeclineModal.test.tsx
  coral/src/app/features/approvals/components/RequestDeclineModal.tsx
  coral/src/app/features/approvals/components/RequestDetailsModal.test.tsx
  coral/src/app/features/approvals/components/RequestDetailsModal.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/topic/topic-api.ts
Labels: Housekeeping, Frontend

#703 refactor(coral): Make status columns in approvals consistent
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/schemas/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/app/features/approvals/topics/hooks/useTableFilters.tsx
  coral/src/app/features/approvals/utils/request-status-helper.ts
Labels: Housekeeping, Frontend

#721 chore(coral): Update DS to 1.8.1
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
Labels: Frontend

#718 feat(coral): Add approving/rejecting schema request
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/domain/schema-request/schema-request-api.ts
Labels: enhancement, Frontend

#725 feat(coral): Approvals: Fix copy, remove feature flag
  coral/src/app/hooks/useFeatureFlag.ts
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/pages/approvals/index.tsx
  coral/vite.config.ts
Labels: Housekeeping, Frontend
