Repository Aiven-Open/klaw, pull requests merged in 2023-07, with the labels that each got.

#1425 fix(coral): Fix flash of stale content on TopicOverview
  coral/src/app/features/topics/details/TopicDetails.tsx
Labels: bug, Frontend

#1430 refactor(coral): Add generic EntityDetailsHeader
  coral/src/app/features/components/EntityDetailsHeader.test.tsx
  coral/src/app/features/components/EntityDetailsHeader.tsx
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicDetailsHeader.test.tsx
Labels: Housekeeping, Frontend

#1420 feat(coral): Topic details - Promote topic
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.test.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/pages/topics/promotion-request.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/domain/topic/index.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-types.ts
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#1434 feat(coral): Connector details - Overview: Add Header component, environment switching, render connector info
  coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/connectors/details/overview/ConnectorOverview.test.tsx
  coral/src/app/features/connectors/details/overview/ConnectorOverview.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/router.tsx
Labels: enhancement, Frontend

#1443 refactor(coral): disable edit button for topic/connectors while data is updated
  coral/src/app/features/components/EntityDetailsHeader.test.tsx
  coral/src/app/features/components/EntityDetailsHeader.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
Labels: Frontend

#1436 feat(coral): Topic details - Add Edit topic
  coral/src/app/features/components/EntityDetailsHeader.test.tsx
  coral/src/app/features/components/EntityDetailsHeader.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/form-schemas/topic-request-form.ts
  coral/src/app/pages/topics/edit-request.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/domain/topic/index.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#1450 fix(core): fix documentation properties naming in ConnectorOverview
  coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/model/response/ConnectorOverview.java
  core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
  core/src/main/resources/static/js/connectorOverview.js
  core/src/main/resources/templates/connectorOverview.html
  openapi.yaml
Labels: Housekeeping, Backend, Frontend

#1454 refactor(coral): Update comments 🧹
  coral/src/__mocks__/react-markdown.tsx
  coral/src/app/components/FileInput.tsx
  coral/src/app/components/Form.tsx
  coral/src/app/context-provider/AuthProvider.tsx
  coral/src/app/features/requests/components/DeleteRequestDialog.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/main.module.css
  coral/src/app/pages/topics/schema-request.tsx
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/topic/topic-transformer.ts
Labels: Frontend

#1459 refactor(coral): Add toast notification to switch-team.
  coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
  coral/src/app/features/team-info/SwitchTeamsDropdown.tsx
  coral/src/app/features/team-info/TeamInfo.test.tsx
Labels: Frontend

#1461 refactor(coral): Improve error handling for documentation
  coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.tsx
  coral/src/domain/helper/documentation-helper.ts
Labels: Frontend

#1460 fix(coral): MD reference link unclickable
  coral/src/app/components/documentation/DocumentationEditor.tsx
Labels: bug, Frontend

#1457 (fix/refactor): Followup for Promote and Edit topic requests
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
Labels: bug, Housekeeping, Frontend

#1456 fix(coral): Show appropriate message when not authorized to see password
  coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.test.tsx
  coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.tsx
Labels: bug, Frontend

#1469 refactor: Use ClusterStatus enum instead of strings for clusterStatus and envStatus
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/dao/Env.java
  core/src/main/java/io/aiven/klaw/dao/KwClusters.java
  core/src/main/java/io/aiven/klaw/model/response/EnvModelResponse.java
  core/src/main/java/io/aiven/klaw/model/response/EnvUpdatedStatus.java
  core/src/main/java/io/aiven/klaw/model/response/KwClustersModelResponse.java
  core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
  core/src/main/java/io/aiven/klaw/service/EnvControllerService.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  core/src/main/java/io/aiven/klaw/service/ServerConfigService.java
  core/src/main/resources/static/js/envs.js
  core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
  core/src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java
  core/src/test/java/io/aiven/klaw/service/ServerConfigServiceTest.java
  openapi.yaml
Labels: Backend

#1471 feat(coral) - Connector details : Add connector history tab
  coral/src/app/features/connectors/details/history/ConnectorHistory.test.tsx
  coral/src/app/features/connectors/details/history/ConnectorHistory.tsx
  coral/src/app/router.tsx
Labels: enhancement, Frontend

#1451 feat(coral): Add cluster details to TopicOverview
  coral/README.md
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/queries/useExtendedEnvironments.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.test.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/overview/components/ClusterDetails.test.tsx
  coral/src/app/features/topics/details/overview/components/ClusterDetails.tsx
  coral/src/domain/cluster/cluster-api.msw.ts
  coral/src/domain/cluster/cluster-api.ts
  coral/src/domain/cluster/cluster-types.ts
  coral/src/domain/cluster/index.ts
  coral/src/domain/environment/environment-api.msw.ts
  coral/src/domain/environment/environment-api.ts
  coral/src/services/test-utils/custom-queries.ts
Labels: Frontend

#1476 fix(coral) - Topic/Connector details: fix tab content flicker on select
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
Labels: bug, Frontend

#1481 housekeeping(coral): Upgrade `prettier` to `3.0.0`
  coral/.prettierrc
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/components/Form.tsx
  coral/src/app/features/topics/details/messages/useOffsetFilter.tsx
  coral/src/app/features/topics/request/utils.ts
  coral/src/services/api.ts
Labels: Housekeeping, Frontend

#1480 refactor(coral): Add DYNAMIC_API_PATHS
  coral/src/domain/team/team-api.ts
  coral/src/services/api.ts
Labels: Housekeeping, Frontend

#1491 feat(coral): Add createClaimTopicRequest domain
  coral/src/domain/topic/index.ts
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend

#1493 feat(coral): Add cluster status in Topic overview
  coral/src/app/features/topics/details/overview/components/ClusterDetails.test.tsx
  coral/src/app/features/topics/details/overview/components/ClusterDetails.tsx
Labels: Frontend

#1488 feat(coral) - Connector details: request connector deletion
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/connectors/details/settings/ConnectorSettings.test.tsx
  coral/src/app/features/connectors/details/settings/ConnectorSettings.tsx
  coral/src/app/features/connectors/details/settings/components/ConnectorDeleteConfirmationModal.test.tsx
  coral/src/app/features/connectors/details/settings/components/ConnectorDeleteConfirmationModal.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/connector-types.ts
  coral/src/domain/connector/index.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-types.ts
Labels: enhancement, Frontend

#1508 fix(coral): Fix deprecated components and props in Form.tsx
  coral/src/app/components/Form.tsx
Labels: Housekeeping, Frontend

#1506 fix(docs): Minor typos and formatting issues
  coral/docs/development-with-local-klaw.md
  coral/docs/development-with-remote-api.md
  coral/docs/development-witout-api.md
Labels: documentation

#1509 feat(coral): Add editConnectorRequest
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/index.ts
Labels: enhancement, Frontend

#1507 feat(docs): Improvement to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1520 refactor(coral): Add helper function to create URL that supports our routing
  coral/src/services/get-meta-env.ts
  coral/src/services/url-coral-klaw-enabled.test.ts
  coral/src/services/url-coral-klaw-enabled.ts
Labels: Frontend

#1510 feat(coral): Add connector update route and page behind a FF
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/pages/connectors/edit-request.tsx
  coral/src/app/pages/topics/edit-request.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#1513 feat(coral): Improve promotion information for schema
  coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.test.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.tsx
  coral/src/domain/promotion/index.ts
  coral/src/domain/promotion/promotion-types.ts
Labels: Frontend

#1523 feat(coral): Connector details: Edit connector
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
  coral/src/app/pages/connectors/edit-request.tsx
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/connector-types.ts
  coral/src/domain/connector/index.ts
Labels: enhancement, Frontend

#1541 refactor(coral): Add [entity] to 'Description' to be more precise
  coral/src/app/features/components/ConnectorDetailsModalContent.test.tsx
  coral/src/app/features/components/ConnectorDetailsModalContent.tsx
  coral/src/app/features/components/TopicDetailsModalContent.test.tsx
  coral/src/app/features/components/TopicDetailsModalContent.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
Labels: Frontend

#1542 feat(coral): Add missing states for Claim topic banner
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicClaimBanner.test.tsx
  coral/src/app/features/topics/details/components/TopicClaimBanner.tsx
Labels: enhancement, Frontend

#1544 refactor(coral): Add (read-only) to labels for readonly elements
  coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameField.test.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameField.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameOrPrefixField.test.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameOrPrefixField.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/features/topics/schema-request/components/TopicSchema.test.tsx
  coral/src/app/features/topics/schema-request/components/TopicSchema.tsx
  coral/src/app/pages/topics/schema-request.test.tsx
Labels: Frontend

#1547 fix(coral): Connector details: Render only connector config, add header
  coral/src/app/features/connectors/details/overview/ConnectorOverview.test.tsx
  coral/src/app/features/connectors/details/overview/ConnectorOverview.tsx
Labels: bug, Frontend
