Repository Aiven-Open/klaw, pull requests merged in 2023-06, with the labels that each got.

#1306 feat(coral) Topic overview - Add topic history view and table [epic #1299]
  coral/src/app/features/topics/details/history/TopicHistory.test.tsx
  coral/src/app/features/topics/details/history/TopicHistory.tsx
  coral/src/app/pages/topics/details/history/index.tsx
  coral/src/app/router.tsx
  core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
  core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
Labels: enhancement, Frontend

#1308 fix(coral): Show loading state instead of stale data
  coral/src/app/features/topics/details/TopicDetails.tsx
Labels: bug, Frontend

#1310 refactor(coral): Enable passing env through query for schema requests
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: Frontend

#1305 feat(coral): Topic overview - Overview tab
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/StatsDisplay.test.tsx
  coral/src/app/features/topics/details/components/StatsDisplay.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/app/features/topics/details/history/TopicHistory.test.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.test.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/overview/index.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
  coral/src/app/features/topics/details/utils.test.ts
  coral/src/app/features/topics/details/utils.ts
  coral/src/app/pages/topics/details/overview/index.tsx
Labels: enhancement, Frontend

#1313 fix(coral): link to angular for topic overview if feature flag is not enabled.
  coral/src/app/features/topics/browse/components/TopicTable.test.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
  coral/src/app/features/topics/browse/utils/create-topic-overview-link.test.ts
  coral/src/app/features/topics/browse/utils/create-topic-overview-link.ts
Labels: bug, Frontend

#1323 feat(coral): Update styles for page header topic details
  coral/src/app/features/topics/details/components/TopicDetailsHeader.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsHeader.tsx
Labels: enhancement, Frontend

#1314 feat(coral): Topic details schema - add view with mocked data
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/features/topics/details/components/StatsDisplay.test.tsx
  coral/src/app/features/topics/details/components/StatsDisplay.tsx
  coral/src/app/features/topics/details/history/TopicHistory.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.tsx
  coral/src/app/features/topics/details/schema/components/SchemaStats.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaStats.tsx
  coral/src/app/images/topic-details-schema-Illustration.svg
  coral/src/app/pages/topics/details/schema/index.tsx
  coral/src/app/router.tsx
  coral/vite.config.ts
Labels: enhancement, Frontend

#1336 fix(coral): Fix incorrectly displayed 0 values in `StatsDisplay`
  coral/src/app/features/topics/details/components/StatsDisplay.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
Labels: bug, Frontend

#1346 style(coral): Add custom theme
  coral/src/app/accessibility.module.css
  coral/src/app/components/AuthenticationRequiredAlert.tsx
  coral/src/app/components/Modal.tsx
  coral/src/app/layout/main-navigation/MainNavigationLink.module.css
  coral/src/app/main.module.css
  coral/src/app/pages/not-found/index.tsx
Labels: Frontend

#1344 feat(coral): Topic details - Schema data and switching versions
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/app/features/topics/details/history/TopicHistory.test.tsx
  coral/src/app/features/topics/details/history/TopicHistory.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/model/response/SchemaDetailsPerEnv.java
  openapi.yaml
Labels: enhancement, Frontend

#1352 refactor(coral): Replace temp dialog with toast
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/pages/topics/schema-request.test.tsx
Labels: Frontend

#1355 fix(coral): Harmonize toast copy
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: Housekeeping, Frontend

#1353 feat(coral): Topic details - Schema promotion flow
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.tsx
  coral/src/domain/schema-request/index.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/schema-request/schema-request-types.ts
Labels: enhancement, Frontend

#1371 chore(coral): Update testing dependencies
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.test.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
Labels: Housekeeping, Frontend

#1373 docs(coral): Update reference to enable-coral-in-springboot in docs
  coral/README.md
Labels: documentation

#1375 docs/refactor: Remove msw in app and from documentation
  coral/README.md
  coral/docs/README.md
  coral/docs/directory-structure.md
  coral/docs/mock-api-for-development.md
  coral/mockServiceWorker.js
  coral/package.json
  coral/src/app/features/login/components/LoginForm.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/main.tsx
  coral/src/domain/acl/acl-api-msw.ts
  coral/src/domain/auth-user/auth-user-api.msw.ts
  coral/src/domain/environment/environment-api.msw.ts
  coral/src/domain/topic/topic-api.msw.ts
  coral/src/domain/topic/topic-api.test.ts
  coral/src/services/api-mocks/browser.ts
  coral/src/services/api-mocks/types.ts
  coral/src/services/api.test.ts
  coral/src/services/test-utils/api-mocks/server.ts
  coral/src/types/global.d.ts
Labels: documentation, Housekeeping, Frontend

#1377 fix(coral): Remove superfluous field properties
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
  coral/src/app/features/requests/connectors/components/ConnectorRequestsTable.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
  coral/src/app/features/topics/details/history/TopicHistory.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx
Labels: Housekeeping, Frontend

#1382 feat(coral): Add `getAivenServiceAccountDetails` and `getConsumerOffsets`
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/acl/acl-types.ts
Labels: enhancement, Frontend

#1405 feat(coral): Connector details - Add `getConnectorOverview` `domain` handler
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/connector-transformer.ts
  coral/src/domain/connector/connector-types.ts
  coral/src/domain/connector/index.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/model/response/ConnectorOverview.java
  openapi.yaml
Labels: enhancement, Backend, Frontend

#1406 feat(coral): Connector details: Add Connector details tabbed layout
  coral/src/app/features/connectors/browse/components/ConnectorTable.test.tsx
  coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/topics/browse/utils/create-topic-overview-link.ts
  coral/src/app/pages/connectors/details/index.test.tsx
  coral/src/app/pages/connectors/details/index.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#1417 refactor(coral): Remove template string where it could hide type errors.
  coral/src/app/components/FileInput.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/components/AclDetailsModalContent.test.tsx
  coral/src/app/features/components/AclDetailsModalContent.tsx
  coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx
  coral/src/app/layout/main-navigation/MainNavigationSubmenuList.test.tsx
Labels: Frontend
