Repository Aiven-Open/klaw, pull requests merged in 2023-05, with the labels that each got.

#1106 refactor(coral) Add nvmrc and define more broad version
  coral/.nvmrc
  coral/README.md
  coral/package.json
Labels: Frontend

#1136 fix(coral): Update payload and typing in schema request
  coral/src/domain/schema-request/schema-request-api.ts
Labels: bug, Frontend

#1119 feat(coral): Add Request a new dropdown navigation in Header
  coral/docs/feature-flags.md
  coral/src/app/components/Form.test.tsx
  coral/src/app/components/Form.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameField.test.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameField.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameOrPrefixField.test.tsx
  coral/src/app/features/topics/acl-request/fields/TopicNameOrPrefixField.tsx
  coral/src/app/features/topics/acl-request/form-schemas/topic-acl-request-consumer.ts
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/acl-request/queries/useExtendedEnvironments.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/features/topics/schema-request/form-schemas/topic-schema-request-form.ts
  coral/src/app/layout/Layout.test.tsx
  coral/src/app/layout/header/HeaderNavigation.test.tsx
  coral/src/app/layout/header/HeaderNavigation.tsx
  coral/src/app/pages/topics/schema-request.test.tsx
  coral/src/app/pages/topics/schema-request.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#1137 fix(coral): Add z-index to skip link for focus-visible
  coral/src/app/layout/page/BasePage.tsx
Labels: Frontend

#1145 fix(coral): Make all env available when using prefix in ACL request
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
Labels: bug, Frontend

#1144 fix(coral): Remove superfluous `defaultValue` in `TopicSchemaRequest`
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: bug, Frontend

#1121 fix(coral): Use correct environments GET endpoints, rename domain fn to be more explicit
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.test.tsx
  coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/queries/useExtendedEnvironments.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/pages/requests/acls/index.test.tsx
  coral/src/app/pages/requests/connectors/index.test.tsx
  coral/src/app/pages/requests/schemas/index.test.tsx
  coral/src/app/pages/requests/topics/index.test.tsx
  coral/src/app/pages/topics/index.test.tsx
  coral/src/app/pages/topics/schema-request.test.tsx
  coral/src/domain/environment/environment-api.msw.ts
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/environment/index.ts
  coral/src/services/api.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
  openapi.yaml
Labels: bug, Frontend

#1240 feat(coral): Add `getTopicOverview` to `topic` `domain`
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend

#1234 feat(coral): Topic overview layout page template and tabs
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicDetailsHeader.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/app/features/topics/details/overview/index.tsx
  coral/src/app/pages/requests/schemas/index.test.tsx
  coral/src/app/pages/topics/details/index.test.tsx
  coral/src/app/pages/topics/details/index.tsx
  coral/src/app/pages/topics/overview.test.tsx
  coral/src/app/pages/topics/overview.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/services/feature-flags/route-utils.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#1256 fix(coral): Remove resetPassword path, add resetToken and resetPasswordWithToken
  coral/src/services/api.ts
Labels: bug, Frontend

#1255 feat(coral): Topic overview, subscriptions - Add Subscriptions table component
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx
  coral/src/app/router.tsx
  coral/src/domain/topic/topic-types.ts
Labels: enhancement, Frontend

#1097 feat(coral): Enable users to change teams in coral
  coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
  coral/src/app/features/team-info/SwitchTeamsDropdown.tsx
  coral/src/app/features/team-info/TeamInfo.test.tsx
  coral/src/app/features/team-info/TeamInfo.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/domain/team/index.ts
  coral/src/domain/team/team-api.ts
Labels: enhancement, Frontend

#1270 chore(coral): Update aquarium -> 1.20.0
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/layout/header/HeaderNavigation.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
Labels: Housekeeping, Frontend

#1277 feat(coral): Use SegmentedControlGroup for subscriptions options
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
Labels: enhancement, Frontend

#1293 fix(coral): fix redirect on first load for Request submission from Subscriptions tab
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/acl-request/queries/useExtendedEnvironments.tsx
Labels: bug, Frontend

#1287 refactor(CAMA): use context for filters handling
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/filters/AclTypeFilter.test.tsx
  coral/src/app/features/components/filters/AclTypeFilter.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.tsx
  coral/src/app/features/components/filters/MyRequestsFilter.test.tsx
  coral/src/app/features/components/filters/MyRequestsFilter.tsx
  coral/src/app/features/components/filters/RequestTypeFilter.test.tsx
  coral/src/app/features/components/filters/RequestTypeFilter.tsx
  coral/src/app/features/components/filters/SearchFilter.test.tsx
  coral/src/app/features/components/filters/SearchFilter.tsx
  coral/src/app/features/components/filters/StatusFilter.test.tsx
  coral/src/app/features/components/filters/StatusFilter.tsx
  coral/src/app/features/components/filters/TeamFilter.test.tsx
  coral/src/app/features/components/filters/TeamFilter.tsx
  coral/src/app/features/components/filters/useFiltersContext.test.tsx
  coral/src/app/features/components/filters/useFiltersContext.tsx
  coral/src/app/features/components/filters/useFiltersValues.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
  coral/src/app/pages/requests/acls/index.tsx
  coral/src/app/pages/requests/connectors/index.tsx
  coral/src/app/pages/requests/schemas/index.tsx
  coral/src/app/pages/requests/topics/index.tsx
Labels: Housekeeping, Frontend

#1294 feat(coral): Topic subscriptions - Add stats for consumers and producers
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
Labels: enhancement, Frontend

#1292 feat(coral): Topic Detail: get and pass relevant topic information from TopicDetails component
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicDetailsHeader.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsHeader.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
  coral/src/app/features/topics/overview/messages/TopicMessages.tsx
  coral/src/app/pages/topics/details/index.test.tsx
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/environment/index.ts
  coral/src/domain/topic/index.ts
  coral/src/domain/topic/topic-types.ts
Labels: enhancement, Frontend

#1301 fix(coral): Add default value for context environmentId in useTopicDetails
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
Labels: bug, Frontend

#1302 feat(coral): Add `getSchemaOfTopic` to `topic-api` domain
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-types.ts
  coral/src/services/api-helper.ts
Labels: enhancement, Frontend

#1304 refactor(coral): Re-structure topic panel content pages
  coral/src/app/features/topics/details/messages/TopicMessages.test.tsx
  coral/src/app/features/topics/details/messages/TopicMessages.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageItem.test.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageItem.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageList.test.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageList.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.test.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.tsx
  coral/src/app/features/topics/details/messages/useOffsetFilter.test.tsx
  coral/src/app/features/topics/details/messages/useOffsetFilter.tsx
  coral/src/app/pages/topics/details/messages/index.tsx
  coral/src/app/pages/topics/details/overview/index.tsx
  coral/src/app/pages/topics/details/subscriptions/index.tsx
  coral/src/app/router.tsx
Labels: Frontend
