Repository Aiven-Open/klaw, pull requests merged in 2023-09, with the labels that each got.

#1714 feat(coral): Claim connector UI
  coral/src/app/features/components/ClaimConfirmationModal.test.tsx
  coral/src/app/features/components/ClaimConfirmationModal.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicClaimConfirmationModal.test.tsx
  coral/src/app/pages/connectors/details/index.test.tsx
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/connector-types.ts
  coral/src/domain/connector/index.ts
Labels: enhancement, Frontend

#1729 refactor(coral): Update monaco editor mock
  coral/test-setup/mock-monaco-editor.tsx
Labels: Housekeeping, Frontend

#1727 feat(coral): Add promotion banner to connector promotion
  coral/src/app/features/connectors/details/components/ConnectorPromotionBanner.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorPromotionBanner.tsx
  coral/src/app/features/connectors/details/overview/ConnectorOverview.test.tsx
  coral/src/app/features/connectors/details/overview/ConnectorOverview.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
Labels: Frontend

#1735 build(deps): Update dependencies to fix vulnerabilities
  coral/package.json
  coral/pnpm-lock.yaml
Labels: Frontend

#1713 feat(coral): Add Configuration nav item
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#1723 feact(coral): Add form to request connector promotion
  coral/src/app/features/connectors/request/ConnectorPromotionRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorPromotionRequest.tsx
  coral/src/app/features/connectors/request/components/ConnectorSkeletonForm.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
  coral/src/app/pages/connectors/promotion-request.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/index.ts
  coral/src/domain/promotion/index.ts
  coral/src/domain/promotion/promotion-types.ts
  coral/src/domain/topic/index.ts
Labels: Frontend

#1739 feat(coral) - View environments: Add necessary domain entities
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/environment/environment-test-helper.test.ts
  coral/src/domain/environment/environment-test-helper.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/environment/index.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/model/response/EnvModelResponse.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  openapi.yaml
Labels: enhancement, Backend, Frontend

#1743 fix(coral): Fix proper loading state for `SubmitButton` in `Form`
  coral/src/app/components/Form.test.tsx
  coral/src/app/components/Form.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/services/test-utils/render-form.tsx
Labels: Frontend

#1744 fix(coral): Use correct path for paginated envs endpoints
  coral/src/domain/environment/environment-api.ts
Labels: bug, Frontend

#1746 feat(api): Add `totalRecs` to `EnvModelResponse`
  coral/src/domain/environment/environment-test-helper.test.ts
  coral/src/domain/environment/environment-test-helper.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/environment-types.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/helpers/Pager.java
  core/src/main/java/io/aiven/klaw/model/response/EnvModelResponse.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  openapi.yaml
Labels: enhancement, Backend, Frontend

#1750 fix(coral): Add `server` for all test suites
  coral/src/services/test-utils/api-mocks/server.ts
  coral/test-setup/setup-files-after-env.ts
Labels: Frontend

#1757 feat(coral) - View environments: Add all environment pages, add feature components stubs
  coral/src/app/features/configuration/environments/Kafka/KafkaEnvironments.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/KafkaConnectEnvironments.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/SchemaRegistryEnvironments.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/layout/main-navigation/MainNavigationSubmenuList.test.tsx
  coral/src/app/layout/main-navigation/MainNavigationSubmenuList.tsx
  coral/src/app/pages/configuration/environments/kafka-connect/index.tsx
  coral/src/app/pages/configuration/environments/kafka/index.tsx
  coral/src/app/pages/configuration/environments/schema-registry/index.tsx
  coral/src/app/router.tsx
Labels: enhancement, Frontend

#1759 feat(coral) - View environments: add necessary properties to Environment type
  coral/src/app/features/configuration/environments/components/EnvironmentsTabs.test.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/form-schemas/topic-request-form.ts
  coral/src/domain/environment/environment-test-helper.ts
  coral/src/domain/environment/environment-transformer.test.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/topic/topic-api.test.ts
Labels: enhancement, Frontend

#1755 build(deps/dev-deps): Update prettier, monaco-editor-react, types/react
  .gitignore
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/domain/topic/topic-transformer.test.ts
  e2e/playwright-report/index.html
  e2e/test-results/test.ts
Labels: Frontend

#1761 feat(coral) - View environments: Add tables rendering list of environments
  coral/src/app/features/configuration/environments/Kafka/KafkaEnvironments.test.tsx
  coral/src/app/features/configuration/environments/Kafka/KafkaEnvironments.tsx
  coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/KafkaConnectEnvironments.test.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/KafkaConnectEnvironments.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/components/KafkaConnectEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/components/KafkaConnectEnvironmentsTable.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/SchemaRegistryEnvironments.test.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/SchemaRegistryEnvironments.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/components/SchemaRegistryEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/components/SchemaRegistryEnvironmentsTable.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentStatus.test.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentStatus.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentsTabs.tsx
  coral/src/app/features/configuration/environments/hooks/getPaginatedEnvironments.tsx
  coral/src/app/pages/configuration/environments/kafka-connect/index.tsx
  coral/src/app/pages/configuration/environments/kafka/index.tsx
  coral/src/app/pages/configuration/environments/schema-registry/index.tsx
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/environment/index.ts
Labels: enhancement, Frontend

#1772 fix(core): Allow `Pager` to return `pageNo` as `currentPage` when `pageNo` is a stringified int
  core/src/main/java/io/aiven/klaw/helpers/Pager.java
  core/src/test/java/io/aiven/klaw/helpers/PagerTest.java
Labels: Backend

#1774 fix(coral): 🐛 handle not existent topic/connector correctly
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/topic/topic-api.ts
Labels: Frontend

#1763 feat(coral): Add profile dropdown
  coral/src/app/layout/Layout.test.tsx
  coral/src/app/layout/LayoutWithoutNav.test.tsx
  coral/src/app/layout/header/HeaderMenuLink.test.tsx
  coral/src/app/layout/header/HeaderMenuLink.tsx
  coral/src/app/layout/header/HeaderNavigation.test.tsx
  coral/src/app/layout/header/HeaderNavigation.tsx
  coral/src/app/layout/header/ProfileDropdown.module.css
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
  coral/src/domain/auth-user/auth-user-api.ts
  coral/src/domain/auth-user/index.ts
Labels: Frontend

#1788 fix(coral): Show environments: Fix unable to refresh status after first two clicks
  coral/src/app/features/configuration/environments/components/EnvironmentStatus.test.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentStatus.tsx
Labels: bug, Frontend

#1790 fix(coral): Format all .md files with prettier
  .github/ISSUE_TEMPLATE/01_question.md
  .github/ISSUE_TEMPLATE/03_feature.md
  .github/workflows.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  adr/readme.md
  coral/README.md
  coral/docs/accessibility.md
  coral/docs/development-with-local-klaw.md
  coral/docs/development-with-remote-api.md
  coral/docs/development-witout-api.md
  coral/docs/directory-structure.md
  coral/docs/documentation.md
  coral/docs/feature-flags.md
  coral/docs/frontend-testing.md
  core/src/main/java/io/aiven/klaw/dao/migration/README.md
  docker-scripts/README.md
  e2e/README.md
  jmeter/README.md
Labels: Housekeeping, Frontend

#1806 fix: Improve automated PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Housekeeping
