Repository Aiven-Open/klaw, pull requests merged in 2023-10, with the labels that each got.

#1823 docs: Fix condescending language
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#1847 feat(coral): View environments - Add time of last update of environment status
  coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/components/KafkaConnectEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/components/KafkaConnectEnvironmentsTable.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/components/SchemaRegistryEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/components/SchemaRegistryEnvironmentsTable.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentStatus.test.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentStatus.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentsTabs.test.tsx
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/domain/environment/environment-test-helper.ts
  coral/src/domain/environment/environment-transformer.test.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/topic/topic-api.test.ts
Labels: enhancement, Frontend

#1850 fix(coral): Add user and team name to profile dropdown.
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
Labels: bug, Frontend

#1851 fix(coral): Exclude api.d.ts from lint-staged, add md linting
  coral/package.json
  e2e/package.json
Labels: Housekeeping, Frontend

#1816 refactor(coral): replace FlexBox with Box.Flex
  coral/src/app/features/components/AclDetailsModalContent.tsx
  coral/src/app/features/components/ConnectorDetailsModalContent.tsx
  coral/src/app/features/components/SchemaRequestDetails.tsx
  coral/src/app/features/components/TopicDetailsModalContent.tsx
  coral/src/app/features/components/layouts/TableLayout.tsx
  coral/src/app/features/topics/acl-request/forms/SkeletonForm.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageItem.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx
Labels: Housekeeping, Frontend, hacktoberfest-accepted

#1853 chore(core): Add Environments banner to Angular UI
  core/src/main/resources/templates/envs.html
Labels: Housekeeping, Frontend

#1865 fix(coral): Replace `direction` by `flexDirection` on `Box.Flex`
  coral/src/app/features/components/AclDetailsModalContent.tsx
  coral/src/app/features/components/ConnectorDetailsModalContent.tsx
  coral/src/app/features/components/SchemaRequestDetails.tsx
  coral/src/app/features/components/TopicDetailsModalContent.tsx
  coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx
Labels: bug, Frontend

#1852 chore(coral): Remove feature flag gating Environments page
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/router.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: Housekeeping, Frontend

#1863 chore(coral): Split `TopicAclRequest` tests, add `--max-workers` flag to CI tests
  .github/workflows/jobs-coral.yaml
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_consumer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_producer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_shared.test.tsx
Labels: Housekeeping, Frontend

#1902 Refactor(build): remove superfluous docker-compose
  docker-scripts/docker-compose-klaw-v2.yaml
  docker-scripts/docker-compose-klaw.yaml
  docker-scripts/docker-compose-testEnv-v2.yaml
  docker-scripts/docker-compose-testEnv.yaml
  docker-scripts/klaw-docker.sh
Labels: Housekeeping

#1898 feat(coral): Improve Search field (label, description)
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/components/filters/SearchConnectorFilter.test.tsx
  coral/src/app/features/components/filters/SearchConnectorFilter.tsx
  coral/src/app/features/components/filters/SearchFilter.test.tsx
  coral/src/app/features/components/filters/SearchFilter.tsx
  coral/src/app/features/components/filters/SearchTopicFilter.test.tsx
  coral/src/app/features/components/filters/SearchTopicFilter.tsx
  coral/src/app/features/components/layouts/TableLayout.tsx
  coral/src/app/features/configuration/environments/Kafka/KafkaEnvironments.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/KafkaConnectEnvironments.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/SchemaRegistryEnvironments.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
Labels: bug, enhancement, Frontend

#1845 refactor: replace deprecated griditem with Grid.Item
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/components/FileInput.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/components/AclDetailsModalContent.tsx
  coral/src/app/features/components/ConnectorDetailsModalContent.tsx
  coral/src/app/features/components/SchemaRequestDetails.tsx
  coral/src/app/features/components/TopicDetailsModalContent.tsx
  coral/src/app/features/connectors/request/components/ConnectorSkeletonForm.tsx
  coral/src/app/features/topics/acl-request/forms/SkeletonForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/schema/components/SchemaStats.tsx
  coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.tsx
  coral/src/app/layout/page/BasePage.tsx
  coral/src/app/layout/page/BasePageWithoutNav.tsx
Labels: Housekeeping, Frontend, hacktoberfest-accepted

#1854 fix(coral): Replace deprecated typography
  coral/src/app/components/AuthenticationRequiredAlert.tsx
  coral/src/app/components/Modal.tsx
  coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.tsx
  coral/src/app/features/team-info/TeamInfo.tsx
  coral/src/app/pages/not-found/index.tsx
Labels: Housekeeping, Frontend, hacktoberfest-accepted

#1925 refactor(coral): Replace depracted GridItem in EnvironmentStatus
  coral/src/app/features/configuration/environments/components/EnvironmentStatus.tsx
Labels: Housekeeping, Frontend

#1930 refactor(coral): Remove handcrafted Environment type
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
  coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.tsx
  coral/src/app/features/configuration/environments/KafkaConnect/components/KafkaConnectEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/SchemaRegistry/components/SchemaRegistryEnvironmentsTable.test.tsx
  coral/src/app/features/configuration/environments/components/EnvironmentsTabs.test.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
  coral/src/app/features/connectors/request/ConnectorPromotionRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
  coral/src/app/features/requests/schemas/utils/mocked-api-responses.ts
  coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/request/form-schemas/topic-request-form.ts
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/environment/environment-test-helper.ts
  coral/src/domain/environment/environment-transformer.test.ts
  coral/src/domain/environment/environment-transformer.ts
  coral/src/domain/environment/environment-types.ts
  coral/src/domain/topic/topic-api.test.ts
Labels: Housekeeping, Frontend

#1932 feat(coral) - Add breadcrumbs to `EntityDetailsHeader`
  coral/src/app/features/components/EntityDetailsHeader.test.tsx
  coral/src/app/features/components/EntityDetailsHeader.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/pages/BreadCrumbsWithLinks.test.tsx
  coral/src/app/pages/BreadCrumbsWithLinks.tsx
Labels: enhancement, Frontend

#1943 refactor(coral): Remove `msw` dependency for `TopicRequest` tests
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/domain/topic/topic-api.msw.ts
  coral/src/domain/topic/topic-api.test.ts
Labels: Housekeeping, Frontend

#1824 refactor(coral): Replace hacky notification solution in ProfileDropdown
  coral/src/app/layout/Layout.test.tsx
  coral/src/app/layout/LayoutWithoutNav.test.tsx
  coral/src/app/layout/header/HeaderNavigation.test.tsx
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
Labels: enhancement, Frontend, hacktoberfest-accepted
