Repository Aiven-Open/klaw, pull requests merged in 2023-11, with the labels that each got.

#1944 refactor(coral): Move `mockedEnvironmentResponse` to helper file
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/domain/environment/environment-api.msw.ts
  coral/src/domain/environment/environment-test-helper.ts
Labels: Housekeeping, Frontend

#1946 refactor(coral): Remove `msw` from `TopicAclRequest` tests
  coral/src/app/features/topics/acl-request/TopicAclRequest_consumer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_producer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_shared.test.tsx
  coral/src/domain/acl/acl-api-msw.ts
  coral/src/domain/cluster/cluster-api-test-helper.ts
Labels: Housekeeping, Frontend

#1949 refactor(coral): remove deprecated `msw` fixtures and unused login
  coral/src/app/features/login/Login.test.tsx
  coral/src/app/features/login/Login.tsx
  coral/src/app/features/login/components/LoginForm.test.tsx
  coral/src/app/features/login/components/LoginForm.tsx
  coral/src/app/features/login/hooks/useLoginUser.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_consumer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_producer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_shared.test.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/router.tsx
  coral/src/domain/auth-user/auth-user-api.msw.ts
  coral/src/domain/auth-user/auth-user-api.ts
  coral/src/domain/auth-user/auth-user-types.ts
  coral/src/domain/auth-user/index.ts
  coral/src/domain/environment/environment-api.msw.ts
  coral/src/domain/environment/index.ts
  coral/src/domain/topic/topic-api.msw.ts
  coral/src/domain/topic/topic-test-helper.ts
  coral/src/services/api.test.ts
  coral/test-setup/setup-files-after-env.ts
Labels: Housekeeping, Frontend

#1950 refactor(coral): Upgrade `msw` -> v2.0.1, remove `crypto` dependencies
  coral/jest.config.ts
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/services/api.test.ts
  coral/src/services/test-utils/api-mocks/server.ts
  coral/test-setup/setup-files-after-env.ts
Labels: Housekeeping, Frontend

#1991 fix(coral) - Fix `TableLayout` filters row
  coral/src/app/features/components/layouts/TableLayout.tsx
Labels: enhancement, Frontend

#2006 feat(coral): Topic messages: allow users to fetch according to partition ID and custom offset
  coral/src/app/accessibility.module.css
  coral/src/app/features/topics/details/messages/TopicMessages.test.tsx
  coral/src/app/features/topics/details/messages/TopicMessages.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageFilters.test.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageFilters.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.test.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.tsx
  coral/src/app/features/topics/details/messages/useMessagesFilters.test.tsx
  coral/src/app/features/topics/details/messages/useMessagesFilters.tsx
  coral/src/app/features/topics/details/messages/useOffsetFilter.test.tsx
  coral/src/app/features/topics/details/messages/useOffsetFilter.tsx
  coral/src/domain/topic/topic-api.ts
Labels: enhancement, Frontend

#2010 refactor(coral): Align info banner with links to old interface
  coral/src/app/components/documentation/DocumentationEditor.test.tsx
  coral/src/app/components/documentation/DocumentationView.test.tsx
  coral/src/app/features/components/EntityDetailsHeader.test.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/connectors/details/overview/ConnectorOverview.test.tsx
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/pages/approvals/acls/index.tsx
  coral/src/app/pages/approvals/connectors/index.tsx
  coral/src/app/pages/approvals/index.tsx
  coral/src/app/pages/approvals/schemas/index.tsx
  coral/src/app/pages/approvals/topics/index.tsx
  coral/src/app/pages/configuration/environments/index.tsx
  coral/src/app/pages/configuration/environments/kafka-connect/index.tsx
  coral/src/app/pages/configuration/environments/kafka/index.tsx
  coral/src/app/pages/configuration/environments/schema-registry/index.tsx
  coral/src/app/pages/configuration/teams/index.tsx
  coral/src/app/pages/configuration/users/index.tsx
  coral/src/app/pages/connectors/details/index.tsx
  coral/src/app/pages/requests/acls/index.test.tsx
  coral/src/app/pages/requests/acls/index.tsx
  coral/src/app/pages/requests/connectors/index.test.tsx
  coral/src/app/pages/requests/connectors/index.tsx
  coral/src/app/pages/requests/index.tsx
  coral/src/app/pages/requests/schemas/index.test.tsx
  coral/src/app/pages/requests/schemas/index.tsx
  coral/src/app/pages/requests/topics/index.test.tsx
  coral/src/app/pages/requests/topics/index.tsx
  coral/src/app/pages/topics/details/index.tsx
  coral/src/app/router_utils.ts
  coral/src/services/test-utils/custom-queries.ts
Labels: Frontend

#2024 feat(coral): Add change-password route, page and links
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/pages/user-information/change-password/index.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
Labels: enhancement, Frontend

#2017 fix(coral): Subscription details: Fix consumer offsets
  cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/consumergroup/OffsetDetails.java
  coral/package.json
  coral/src/app/features/topics/details/subscriptions/components/ConsumerOffsetsValues.test.tsx
  coral/src/app/features/topics/details/subscriptions/components/ConsumerOffsetsValues.tsx
  coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.test.tsx
  coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.tsx
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/model/cluster/consumergroup/OffsetDetails.java
  core/src/main/java/io/aiven/klaw/model/response/OffsetDetails.java
  openapi.yaml
Labels: bug, enhancement, Backend, Frontend

#2040 housekeeping(coral): Update `aquarium` -> `1.47.0`
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/components/Form.test.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.tsx
  coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
  coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx
  coral/src/app/layout/header/HeaderNavigation.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
Labels: Housekeeping, Frontend

#2039 refactor(coral): Update Form to not handle events for readonly or disabled elements
  coral/src/app/components/Form.tsx
Labels: Frontend

#2038 feat(coral): User information: change password
  coral/src/app/components/Dialog.tsx
  coral/src/app/features/user-information/change-password/ChangePasswordForm.test.tsx
  coral/src/app/features/user-information/change-password/ChangePasswordForm.tsx
  coral/src/app/features/user-information/change-password/changePasswordFormSchema.ts
  coral/src/app/pages/user-information/change-password/index.tsx
  coral/src/domain/user/user-api.ts
Labels: enhancement, Frontend

#2049 feat(coral): Tenant info: add route, page, `MainNavigation` and `ProfileDropdown` links
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/pages/user-information/tenant-info/index.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
Labels: enhancement, Frontend

#2041 feat(coral): Remove feature flag `FEATURE_FLAG_USER_TEAMS`
  coral/src/app/features/configuration/users/Users.test.tsx
  coral/src/app/features/configuration/users/Users.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/layout/page/BasePage.tsx
  coral/src/app/router.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: Frontend

#2057 feat(coral): View and update user profile
  coral/src/app/features/user-information/profile/Profile.test.tsx
  coral/src/app/features/user-information/profile/Profile.tsx
  coral/src/app/features/user-information/profile/components/SkeletonProfile.tsx
  coral/src/app/features/user-information/profile/components/TeamsOverview.test.tsx
  coral/src/app/features/user-information/profile/components/TeamsOverview.tsx
  coral/src/app/features/user-information/profile/form-schema/profile-form.ts
  coral/src/app/pages/user-information/profile/index.tsx
  coral/src/domain/user/index.ts
  coral/src/domain/user/user-api.ts
Labels: Frontend
