Repository Aiven-Open/klaw, pull requests merged in 2023-08, with the labels that each got.

#1565 fix(coral): Update vite dep -> 4.4.8
  coral/package.json
  coral/pnpm-lock.yaml
Labels: dependencies, Frontend

#1564 housekeeping(coral): Rename domain handlers
  coral/docs/directory-structure.md
  coral/src/app/features/connectors/details/settings/ConnectorSettings.test.tsx
  coral/src/app/features/connectors/details/settings/ConnectorSettings.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.test.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/pages/topics/schema-request.test.tsx
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/connector/index.ts
  coral/src/domain/schema-request/index.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/topic/index.ts
  coral/src/domain/topic/topic-api.test.ts
  coral/src/domain/topic/topic-api.ts
Labels: Housekeeping, Frontend

#1554 fix(docs): Add maven as requirements, fix typo, clarify some steps
  coral/docs/development-with-local-klaw.md
  coral/proxy/README.md
Labels: documentation, Frontend

#1551 chore(coral): Update Topic and Connector settings copy
  coral/src/app/features/connectors/details/settings/ConnectorSettings.test.tsx
  coral/src/app/features/connectors/details/settings/ConnectorSettings.tsx
  coral/src/app/features/connectors/details/settings/components/ConnectorDeleteConfirmationModal.test.tsx
  coral/src/app/features/connectors/details/settings/components/ConnectorDeleteConfirmationModal.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.test.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.tsx
  coral/src/app/features/topics/details/settings/components/TopicDeleteConfirmationModal.test.tsx
  coral/src/app/features/topics/details/settings/components/TopicDeleteConfirmationModal.tsx
Labels: Housekeeping, Frontend

#1586 style(coral): Update types and format
  coral/proxy/README.md
  coral/types/api.d.ts
Labels: Housekeeping, Frontend

#1548 housekeeping(coral): Update `aquarium` -> 1.33.0
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/accessibility.module.css
  coral/src/app/components/PreviewBanner.tsx
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/components/__snapshots__/InternalLinkButton.test.tsx.snap
  coral/src/app/components/documentation/DocumentationEditor.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/components/layouts/TableLayout.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.tsx
  coral/src/app/features/connectors/details/settings/ConnectorSettings.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
  coral/src/app/features/topics/details/components/TopicClaimBanner.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.tsx
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
  coral/src/app/features/topics/details/settings/TopicSettings.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/layout/main-navigation/MainNavigationLink.module.css
  coral/src/app/layout/main-navigation/MainNavigationLink.tsx
  coral/src/app/layout/main-navigation/MainNavigationSubmenuList.module.css
  coral/src/app/layout/skip-link/SkipLink.module.css
  coral/src/app/main.module.css
  coral/src/app/pages/not-found/index.tsx
Labels: Housekeeping, Frontend

#1600 refactor(coral): Update copy for claim topic
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
  coral/src/app/features/topics/details/components/TopicClaimBanner.test.tsx
  coral/src/app/features/topics/details/components/TopicClaimBanner.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
Labels: Frontend

#1595 fix(coral): Streamline copy for message for approval
  coral/src/app/features/components/AclDetailsModalContent.test.tsx
  coral/src/app/features/components/AclDetailsModalContent.tsx
  coral/src/app/features/components/ConnectorDetailsModalContent.test.tsx
  coral/src/app/features/components/ConnectorDetailsModalContent.tsx
  coral/src/app/features/components/SchemaRequestDetails.test.tsx
  coral/src/app/features/components/SchemaRequestDetails.tsx
  coral/src/app/features/components/TopicDetailsModalContent.test.tsx
  coral/src/app/features/components/TopicDetailsModalContent.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/features/requests/RequestResourcesTabs.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/fields/RemarksField.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/pages/connectors/index.tsx
  coral/src/app/pages/topics/index.test.tsx
  coral/src/app/pages/topics/index.tsx
Labels: Frontend

#1612 refactor(coral): Add description to message offset field
  coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.test.tsx
  coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.tsx
Labels: Frontend

#1611 refactor(coral): Update link for open request to PROMOTE for schema promotion
  coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
Labels: Frontend

#1607 refactor(coral) - Topic/Connector details: Rename "Documentation" to "Readme" and add description
  coral/src/app/components/documentation/DocumentationEditor.test.tsx
  coral/src/app/components/documentation/DocumentationEditor.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.test.tsx
  coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.tsx
  coral/src/app/features/connectors/details/documentation/components/NoDocumentationBanner.test.tsx
  coral/src/app/features/connectors/details/documentation/components/NoDocumentationBanner.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.tsx
  coral/src/app/features/topics/details/documentation/components/NoDocumentationBanner.test.tsx
  coral/src/app/features/topics/details/documentation/components/NoDocumentationBanner.tsx
  coral/src/app/router_utils.ts
Labels: Frontend

#1630 fix(coral): Fix UI and functional bug for approval tables
  coral/src/app/components/Modal.tsx
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/domain/topic/topic-api.ts
Labels: bug, Frontend

#1637 feat(coral): Show info to user when they temp can not edit a topic
  coral/src/app/components/DisabledButtonTooltip.module.css
  coral/src/app/components/DisabledButtonTooltip.test.tsx
  coral/src/app/components/DisabledButtonTooltip.tsx
  coral/src/app/features/components/EntityDetailsHeader.test.tsx
  coral/src/app/features/components/EntityDetailsHeader.tsx
  coral/src/app/features/connectors/details/ConnectorDetails.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/pages/topics/acl-request.tsx
Labels: Frontend

#1599 refactor(coral): Improve UI for schema requests per topic
  coral/src/app/components/InternalLinkButton.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotableOnlyAlert.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotableOnlyAlert.tsx
Labels: Frontend

#1636 feat(coral): Remove feature flags for topic overview, edit and promote
  coral/src/app/features/topics/browse/components/TopicTable.test.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
  coral/src/app/router.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: Frontend

#1635 feat(coral): Add and update preview links in Angular
  core/src/main/resources/static/js/editTopicRequest.js
  core/src/main/resources/templates/browseAcls.html
  core/src/main/resources/templates/connectorOverview.html
  core/src/main/resources/templates/editTopicRequest.html
  core/src/main/resources/templates/execAcls.html
  core/src/main/resources/templates/execConnectors.html
  core/src/main/resources/templates/execSchemas.html
  core/src/main/resources/templates/execTopics.html
  core/src/main/resources/templates/kafkaConnectors.html
  core/src/main/resources/templates/myAclRequests.html
  core/src/main/resources/templates/myConnectorRequests.html
  core/src/main/resources/templates/mySchemaRequests.html
  core/src/main/resources/templates/myTopicRequests.html
  core/src/main/resources/templates/requestAcls.html
  core/src/main/resources/templates/requestConnector.html
  core/src/main/resources/templates/requestSchema.html
  core/src/main/resources/templates/requestTopics.html
Labels: Frontend

#1644 fix(coral): Update handling for open CLAIM request in promotion.
  coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
  coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.tsx
Labels: Frontend

#1649 fix(coral): remove `schemaPromotionDetails` from check for noSchema
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
Labels: Frontend

#1656 fix(coral) Remove "User requests" and "Settings" from nav.
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
Labels: bug, Frontend

#1654 fix(coral): Remove unnecessary re-mounting
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/team-info/SwitchTeamsDropdown.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
Labels: bug, Frontend

#1642 feat(coral): Create reusable `ClaimBanner`, use for claim topic
  coral/src/app/features/components/ClaimBanner.test.tsx
  coral/src/app/features/components/ClaimBanner.tsx
  coral/src/app/features/topics/details/TopicDetails.tsx
  coral/src/app/features/topics/details/components/TopicClaimBanner.test.tsx
Labels: Frontend

#1650 fix(coral): Remove buttons in topic overview for user that are not topic owner
  coral/src/app/features/components/documentation/components/NoDocumentationBanner.test.tsx
  coral/src/app/features/components/documentation/components/NoDocumentationBanner.tsx
  coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.test.tsx
  coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.tsx
  coral/src/app/features/connectors/details/documentation/components/NoDocumentationBanner.test.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.tsx
  coral/src/app/features/topics/details/documentation/components/NoDocumentationBanner.test.tsx
  coral/src/app/features/topics/details/documentation/components/NoDocumentationBanner.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/schema/components/NoSchemaAvailableState.test.tsx
  coral/src/app/features/topics/details/schema/components/NoSchemaAvailableState.tsx
Labels: Frontend

#1663 refactor(coral): Disable/remove requesting new schema (version) request in a few cases
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
  coral/src/app/features/topics/details/schema/components/NoSchemaAvailableState.test.tsx
  coral/src/app/features/topics/details/schema/components/NoSchemaAvailableState.tsx
  coral/src/app/features/topics/details/schema/components/NoSchemaBanner.test.tsx
  coral/src/app/features/topics/details/schema/components/NoSchemaBanner.tsx
  coral/src/app/features/topics/details/schema/components/OpenSchemaRequestAlert.test.tsx
  coral/src/app/features/topics/details/schema/components/OpenSchemaRequestAlert.tsx
Labels: Frontend

#1574 Validate consumer groups in sql
  core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
  core/src/main/java/io/aiven/klaw/repository/AclRepo.java
  core/src/main/java/io/aiven/klaw/service/AclControllerService.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java
  core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
  openapi.yaml
Labels: Backend

#1616 Use find first instead of find all
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
  core/src/main/java/io/aiven/klaw/repository/RegisterInfoRepo.java
Labels: Backend

#1615 Make code for exist methods more concise
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
Labels: Backend

#1676 fix(coral): Update validation for service accounts field
  coral/src/app/features/topics/acl-request/form-schemas/topic-acl-request-shared-fields.ts
Labels: bug, Frontend

#1667 refactor(coral): Update text for blocked actions
  coral/src/app/features/components/ClaimBanner.test.tsx
  coral/src/app/features/components/ClaimBanner.tsx
  coral/src/app/features/components/EntityDetailsHeader.test.tsx
  coral/src/app/features/components/EntityDetailsHeader.tsx
  coral/src/app/features/connectors/details/settings/ConnectorSettings.test.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
  coral/src/app/features/topics/details/components/PromotionBanner.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/schema/components/NoSchemaBanner.test.tsx
  coral/src/app/features/topics/details/schema/components/OpenSchemaRequestAlert.test.tsx
  coral/src/app/features/topics/details/schema/components/OpenSchemaRequestAlert.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.test.tsx
Labels: Frontend

#1674 fix(coral): Use right parameter for `getAivenServiceAccountDetails`.
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.test.tsx
  coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.tsx
  coral/src/domain/acl/acl-api.ts
Labels: Frontend

#1556 Enable jdk20 in ci
  .github/workflows/jobs-maven.yaml
Labels: Backend

#1618 Simplify SelectDataJdbc#getTopicRequestsCounts
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
  core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
  core/src/main/java/io/aiven/klaw/service/RequestStatisticsService.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java
Labels: Backend

#1617 Use find first schema instead find all
  core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
  core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
  core/src/main/java/io/aiven/klaw/repository/MessageSchemaRepo.java
  core/src/main/java/io/aiven/klaw/service/SchemaRegistrySyncControllerService.java
  core/src/test/java/io/aiven/klaw/service/SchemaRegistrySyncControllerServiceTest.java
Labels: Backend

#1688 fix(coral): fix focus style on focusable elements in modals
  coral/src/app/components/Modal.module.css
Labels: Frontend

#1689 refactor(coral): Remove unnecessary tooltips
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/layout/header/HeaderNavigation.tsx
Labels: Frontend

#1702 bug(coral) - ACL request form : Fix error in Topic name field, only fetch `teamId` when needed
  coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
Labels: bug, Frontend
