Repository Aiven-Open/klaw, pull requests merged in 2023-12, with the labels that each got.

#2066 feat(coral): Add notifications for pending requests
  coral/jest.config.ts
  coral/src/app/features/approvals/acls/AclApprovals.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.tsx
  coral/src/app/features/configuration/environments/hooks/getPaginatedEnvironments.tsx
  coral/src/app/features/configuration/users/Users.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.tsx
  coral/src/app/features/requests/acls/AclRequests.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.tsx
  coral/src/app/features/requests/topics/TopicRequests.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/app/features/topics/details/messages/TopicMessages.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/hooks/usePendingRequests.tsx
  coral/src/app/layout/header/HeaderMenuLink.test.tsx
  coral/src/app/layout/header/HeaderMenuLink.tsx
  coral/src/app/layout/header/HeaderNavigation.test.tsx
  coral/src/app/layout/header/HeaderNavigation.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/layout/main-navigation/MainNavigationLink.test.tsx
  coral/src/app/layout/main-navigation/MainNavigationLink.tsx
  coral/src/app/layout/page/BasePage.tsx
  coral/src/app/main.tsx
  coral/src/domain/requests/requests-transformers.test.ts
  coral/src/domain/requests/requests-transformers.ts
  coral/src/domain/requests/requests-types.ts
  coral/test-setup/mock-ds-tabBadge-component.tsx
Labels: enhancement, Frontend

#2091 feat(coral): Add pending requests dropdown in `HeaderNavigation`
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
  coral/src/app/hooks/usePendingRequests.tsx
  coral/src/app/layout/Layout.test.tsx
  coral/src/app/layout/LayoutWithoutNav.test.tsx
  coral/src/app/layout/header/HeaderNavigation.test.tsx
  coral/src/app/layout/header/HeaderNavigation.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
  coral/src/app/layout/header/RequestsDropdown.test.tsx
  coral/src/app/layout/header/RequestsDropdown.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/domain/requests/requests-transformers.test.ts
  coral/src/domain/requests/requests-transformers.ts
  coral/src/domain/requests/requests-types.ts
Labels: enhancement, Frontend

#2094 fix(core): Count claim requests correctly with `getRequestsStatistics`
  core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
  core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java
  core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java
Labels: bug, Backend

#2098 refactor(coral): `TopicSchemaRequest`: replace onSuccess by useEffect
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/pages/topics/schema-request.tsx
Labels: Housekeeping, Frontend

#2113 fix(coral): Update state for open submenu correctly
  coral/src/app/layout/main-navigation/MainNavigationSubmenuList.tsx
Labels: bug, Frontend

#2061 feat(coral): Remove feature flag for User information sections
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/app/layout/header/ProfileDropdown.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/router.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Housekeeping, Frontend

#2116 feat(coral): Remove feature flag for cluster view
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/router.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#2118 refactor(coral): Topic/Connector overview: Fix small flash when switching tabs
  coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
  coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
Labels: Housekeeping, Frontend
