Repository Aiven-Open/klaw, pull requests merged in 2024-02, with the labels that each got.

#2259 fix(coral): Dashboard: Fix console errors, make bar chart vertical
  coral/src/app/features/dashboard/Dashboard.tsx
  coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
Labels: bug, Frontend

#2260 housekeeping(coral): Update aquarium -> 1.53.0
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
  coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
Labels: Housekeeping, Frontend

#2297 feat(coral): Add routes and domain for Add new clusters
  coral/src/app/pages/configuration/clusters/add/index.tsx
  coral/src/app/pages/configuration/clusters/index.test.tsx
  coral/src/app/pages/configuration/clusters/index.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/domain/cluster/cluster-api.ts
  coral/src/domain/cluster/cluster-types.ts
  coral/src/services/feature-flags/route-utils.test.tsx
  coral/src/services/feature-flags/route-utils.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#2301 feat(coral) - Add form for Add new clusters feature
  coral/src/app/features/configuration/clusters/AddNewClusterForm.test.tsx
  coral/src/app/features/configuration/clusters/AddNewClusterForm.tsx
  coral/src/app/features/configuration/clusters/Clusters.test.tsx
  coral/src/app/features/configuration/clusters/components/ClustersTable.test.tsx
  coral/src/app/features/configuration/clusters/schemas/add-new-cluster-form.ts
  coral/src/app/features/topics/details/overview/TopicOverview.test.tsx
  coral/src/app/features/topics/details/overview/components/ClusterDetails.test.tsx
  coral/src/app/pages/configuration/clusters/add/index.tsx
  coral/src/domain/cluster/cluster-api-transformer.test.ts
  coral/src/domain/cluster/cluster-api.ts
  coral/src/domain/cluster/index.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/model/requests/KwClustersModel.java
  core/src/main/java/io/aiven/klaw/model/response/KwClustersModelResponse.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  core/src/main/resources/static/js/envs.js
  core/src/main/resources/static/js/modifyEnvs.js
  core/src/main/resources/templates/addCluster.html
  core/src/main/resources/templates/clusters.html
  core/src/test/java/io/aiven/klaw/MockMethods.java
  openapi.yaml
Labels: enhancement, Backend, Frontend

#2325 fix(coral): New enums for kafkaFlavor and clusterType break existing UI
  coral/src/app/features/configuration/clusters/AddNewClusterForm.test.tsx
  coral/src/app/features/configuration/clusters/AddNewClusterForm.tsx
  coral/src/app/features/configuration/clusters/components/ClustersTable.test.tsx
  coral/src/app/features/configuration/clusters/components/ClustersTable.tsx
  coral/src/app/features/topics/details/overview/components/ClusterDetails.test.tsx
  coral/src/app/features/topics/details/overview/components/ClusterDetails.tsx
  coral/src/domain/cluster/cluster-types.ts
  coral/src/domain/cluster/index.ts
  coral/src/services/formatter/cluster-type-formatter.ts
  coral/src/services/formatter/kafka-flavor-formatter.ts
Labels: bug, Frontend

#2315 feat(coral): Add `application.properties` recap after adding a new cluster
  coral/src/app/components/Clipboard.test.tsx
  coral/src/app/components/Clipboard.tsx
  coral/src/app/components/Modal.tsx
  coral/src/app/features/components/filters/SearchClusterParamFilter.test.tsx
  coral/src/app/features/components/filters/SearchClusterParamFilter.tsx
  coral/src/app/features/configuration/clusters/AddNewClusterForm.test.tsx
  coral/src/app/features/configuration/clusters/AddNewClusterForm.tsx
  coral/src/app/features/configuration/clusters/Clusters.test.tsx
  coral/src/app/features/configuration/clusters/Clusters.tsx
  coral/src/app/features/configuration/clusters/components/ClusterConnectHelpModal.test.tsx
  coral/src/app/features/configuration/clusters/components/ClusterConnectHelpModal.tsx
  coral/src/app/features/configuration/clusters/components/ClustersTable.test.tsx
  coral/src/app/features/configuration/clusters/components/ClustersTable.tsx
Labels: enhancement, Frontend

#2327 feat: Add support for clusterType param in getClustersPaginated endpoint
  coral/src/domain/cluster/cluster-api.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  core/src/main/resources/static/js/envs.js
  openapi.yaml
Labels: Backend
