Repository Aiven-Open/klaw, pull requests merged in 2024-03, with the labels that each got.

#2345 ci: Add explicit permission to gh workflow for openapi types
  .github/workflows/workflow-check-openapi-changes.yaml
Labels: github_actions

#2117 feat(coral): Add CTA to fill in feedback form
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
Labels: enhancement, Frontend

#2346 feat(coral): Add cluster type filter to Clusters table
  coral/src/app/features/components/ClusterTypeFilter.test.tsx
  coral/src/app/features/components/filters/ClusterTypeFilter.tsx
  coral/src/app/features/components/filters/useFiltersContext.test.tsx
  coral/src/app/features/components/filters/useFiltersContext.tsx
  coral/src/app/features/configuration/clusters/Clusters.test.tsx
  coral/src/app/features/configuration/clusters/Clusters.tsx
  coral/src/domain/cluster/cluster-api.ts
  coral/src/services/formatter/cluster-type-formatter.ts
Labels: Frontend

#2352 build(deps): Update aquarium 1.60.1
  coral/package.json
  coral/pnpm-lock.yaml
  coral/src/app/accessibility.module.css
  coral/src/app/components/__snapshots__/Form.test.tsx.snap
  coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
  coral/src/app/features/team-info/TeamInfo.tsx
Labels: dependencies, Frontend

#2354 feat(coral): Allow users to delete clusters
  coral/src/app/components/Dialog.tsx
  coral/src/app/features/configuration/clusters/Clusters.test.tsx
  coral/src/app/features/configuration/clusters/Clusters.tsx
  coral/src/app/features/configuration/clusters/components/ClusterDeleteModal.test.tsx
  coral/src/app/features/configuration/clusters/components/ClusterDeleteModal.tsx
  coral/src/app/features/configuration/clusters/components/ClustersTable.test.tsx
  coral/src/app/features/configuration/clusters/components/ClustersTable.tsx
  coral/src/domain/cluster/cluster-api.ts
  coral/src/domain/cluster/index.ts
Labels: enhancement, Frontend
