Repository Aiven-Open/klaw, pull requests merged in 2024-01, with the labels that each got.

#2140 refactor(coral): Remove target=_blank from links
  coral/src/app/components/PreviewBanner.test.tsx
  coral/src/app/components/PreviewBanner.tsx
  coral/src/app/features/components/SchemaRequestDetails.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotableOnlyAlert.tsx
  coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.tsx
  coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
Labels: Frontend

#2138 refactor(coral): Prevent action for submit and cancel buttons in form while mutation is ongoing
  coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.tsx
  coral/src/app/features/topics/request/TopicEditRequest.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.tsx
  coral/src/app/features/topics/request/TopicRequest.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
  coral/src/app/features/user-information/change-password/ChangePasswordForm.tsx
Labels: Frontend

#2137 deps(coral): Update vite to next major version and add chunk splitting
  coral/package.json
  coral/pnpm-lock.yaml
  coral/vite.config.ts
Labels: Frontend

#2174 fix(coral): Use disabled instead of false for the value of the Switch teams column in Users page
  coral/src/app/features/configuration/users/components/UsersTable.test.tsx
  coral/src/app/features/configuration/users/components/UsersTable.tsx
Labels: Housekeeping, Frontend

#2143 refactor(coral): Add aquarium context to custom render
  coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.test.tsx
  coral/src/app/features/connectors/details/settings/ConnectorSettings.test.tsx
  coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorPromotionRequest.test.tsx
  coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
  coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
  coral/src/app/features/team-info/TeamInfo.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_consumer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_producer.test.tsx
  coral/src/app/features/topics/acl-request/TopicAclRequest_shared.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
  coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
  coral/src/app/features/topics/details/TopicDetails.test.tsx
  coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
  coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
  coral/src/app/features/topics/details/settings/TopicSettings.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/features/topics/request/TopicEditRequest.test.tsx
  coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
  coral/src/app/features/topics/request/TopicRequest.test.tsx
  coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
  coral/src/app/features/user-information/change-password/ChangePasswordForm.test.tsx
  coral/src/app/pages/topics/details/index.test.tsx
  coral/src/services/test-utils/render-with-wrappers.tsx
  coral/types/utils.d.ts
Labels: Frontend

#2139 refactor(coral): Update modal with topic request details for CLAIM requests
  coral/src/app/features/components/TopicDetailsModalContent.test.tsx
  coral/src/app/features/components/TopicDetailsModalContent.tsx
Labels: Frontend

#2141 refactor(coral): Add user and team links
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.test.tsx
  coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
  coral/src/app/features/connectors/browse/components/ConnectorTable.test.tsx
  coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
  coral/src/app/features/connectors/details/history/ConnectorHistory.test.tsx
  coral/src/app/features/connectors/details/history/ConnectorHistory.tsx
  coral/src/app/features/requests/connectors/components/ConnectorRequestsTable.test.tsx
  coral/src/app/features/requests/connectors/components/ConnectorRequestsTable.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.test.tsx
  coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
  coral/src/app/features/topics/browse/components/TopicTable.test.tsx
  coral/src/app/features/topics/browse/components/TopicTable.tsx
  coral/src/app/features/topics/details/history/TopicHistory.test.tsx
  coral/src/app/features/topics/details/history/TopicHistory.tsx
  coral/src/domain/topic/topic-test-helper.ts
Labels: Frontend

#2169 feat(coral): Add Dashboard page
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/pages/dashboard/index.tsx
  coral/src/app/pages/index.test.tsx
  coral/src/app/pages/index.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#2171 feat(coral): Add basic layout and dummy components for Dashboard
  coral/src/app/components/StatsDisplay.test.tsx
  coral/src/app/components/StatsDisplay.tsx
  coral/src/app/features/dashboard/Dasboard.test.tsx
  coral/src/app/features/dashboard/Dashboard.tsx
  coral/src/app/features/topics/details/overview/TopicOverview.tsx
  coral/src/app/features/topics/details/schema/components/SchemaStats.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
  coral/src/app/pages/dashboard/index.tsx
  coral/src/services/test-utils/mock-resize-observer.ts
Labels: enhancement, Frontend

#2163 feat(coral): Add activity log
  coral/src/app/features/activity-log/ActivityLog.test.tsx
  coral/src/app/features/activity-log/ActivityLog.tsx
  coral/src/app/features/activity-log/components/ActivityLogTable.test.tsx
  coral/src/app/features/activity-log/components/ActivityLogTable.tsx
  coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.test.tsx
  coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
  coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
  coral/src/app/features/approvals/utils/request-operation-type-helper.ts
  coral/src/app/features/approvals/utils/request-status-helper.ts
  coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.tsx
  coral/src/app/features/components/filters/RequestTypeFilter.tsx
  coral/src/app/features/components/filters/StatusFilter.tsx
  coral/src/app/features/components/filters/useFiltersContext.tsx
  coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
  coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
  coral/src/app/hooks/usePendingRequests.tsx
  coral/src/app/layout/header/RequestsDropdown.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/pages/activity-log/index.tsx
  coral/src/app/router.tsx
  coral/src/app/router_utils.ts
  coral/src/domain/acl/acl-api.ts
  coral/src/domain/connector/connector-api.ts
  coral/src/domain/environment/environment-api.ts
  coral/src/domain/requests/index.ts
  coral/src/domain/requests/requests-api.ts
  coral/src/domain/requests/requests-transformers.test.ts
  coral/src/domain/requests/requests-transformers.ts
  coral/src/domain/requests/requests-types.ts
  coral/src/domain/schema-request/schema-request-api.ts
  coral/src/domain/topic/topic-api.ts
  coral/src/domain/topic/topic-types.ts
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: enhancement, Frontend

#2176 refactor(coral): Add native select wrapper to handle async option data
  coral/src/app/components/AsyncNativeSelectWrapper.test.tsx
  coral/src/app/components/AsyncNativeSelectWrapper.tsx
Labels: Frontend

#2175 feat(coral): Add data domain entities and data fetching to Dashboard
  coral/src/app/context-provider/AuthProvider.tsx
  coral/src/app/features/dashboard/Dasboard.test.tsx
  coral/src/app/features/dashboard/Dashboard.tsx
  coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
  coral/src/app/hooks/usePendingRequests.tsx
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/app/layout/header/RequestsDropdown.tsx
  coral/src/domain/analytics/analytics-api.ts
  coral/src/domain/analytics/analytics-transformer.test.ts
  coral/src/domain/analytics/analytics-transformer.ts
  coral/src/domain/analytics/analytics-types.ts
  coral/src/domain/analytics/index.ts
  coral/src/domain/auth-user/auth-user-api.ts
  coral/src/domain/auth-user/auth-user-test-helper.ts
  coral/src/domain/auth-user/auth-user-types.ts
Labels: enhancement, Frontend

#2144 fix(coral): Add UI error handling in shared filters
  coral/src/app/features/activity-log/ActivityLog.test.tsx
  coral/src/app/features/approvals/acls/AclApprovals.test.tsx
  coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
  coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
  coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
  coral/src/app/features/components/filters/EnvironmentFilter.tsx
  coral/src/app/features/components/filters/TeamFilter.test.tsx
  coral/src/app/features/components/filters/TeamFilter.tsx
  coral/src/app/features/configuration/users/Users.test.tsx
  coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
  coral/src/app/features/requests/acls/AclRequests.test.tsx
  coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
  coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
  coral/src/app/features/requests/topics/TopicRequests.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
  coral/src/app/pages/requests/acls/index.test.tsx
  coral/src/app/pages/requests/connectors/index.test.tsx
  coral/src/app/pages/requests/schemas/index.test.tsx
  coral/src/app/pages/requests/topics/index.test.tsx
  coral/src/app/pages/topics/index.test.tsx
Labels: bug, Frontend

#2184 feat(coral): Add `useDashboardData` hook
  coral/src/app/features/dashboard/Dasboard.test.tsx
  coral/src/app/features/dashboard/Dashboard.tsx
  coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
  coral/src/app/features/dashboard/hooks/useDashboardData.ts
Labels: enhancement, Frontend

#2189 feat(coral): Add error handling to `usePendingRequests`
  coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
  coral/src/app/hooks/usePendingRequests.tsx
  coral/src/app/layout/Layout.test.tsx
  coral/src/app/layout/LayoutWithoutNav.test.tsx
  coral/src/app/layout/header/RequestsDropdown.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
Labels: enhancement, Frontend

#2185 refactor: Use id instead of name for querying teams
  coral/src/app/features/configuration/users/Users.test.tsx
  coral/src/app/features/configuration/users/Users.tsx
  coral/src/domain/user/user-api.ts
  coral/types/api.d.ts
  core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
  core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
  core/src/main/resources/static/js/manageUsers.js
  core/src/test/java/io/aiven/klaw/controller/UiConfigControllerTest.java
  openapi.yaml
Labels: Housekeeping, Backend, Frontend

#2203 feat(cora): Update login page styles to match `coral`
  core/src/main/java/io/aiven/klaw/service/EmailService.java
  core/src/main/resources/static/assets/css/colors/blue-dark.css
  core/src/main/resources/static/assets/css/colors/blue.css
  core/src/main/resources/static/assets/css/colors/default-dark.css
  core/src/main/resources/static/assets/css/colors/default.css
  core/src/main/resources/static/assets/css/custom.css
  core/src/main/resources/static/assets/css/style.css
  core/src/main/resources/static/assets/scss/_variable.scss
  core/src/main/resources/templates/forgotPassword.html
  core/src/main/resources/templates/login.html
  core/src/main/resources/templates/loginSaas.html
  core/src/main/resources/templates/newADUser.html
  core/src/main/resources/templates/register.html
  core/src/main/resources/templates/registerLdap.html
  core/src/main/resources/templates/registerSaas.html
  core/src/main/resources/templates/registrationReview.html
  core/src/main/resources/templates/registrationReviewSaas.html
  core/src/main/resources/templates/userActivation.html
  e2e/tests/basic-health-check.spec.ts
Labels: enhancement, Frontend

#2223 refactor(core): Redesign reset password flow
  core/src/main/resources/templates/forgotPassword.html
Labels: Housekeeping, Frontend

#2235 feat(coral): Remove feature flag activity log
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/router.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: Frontend

#2234 feat(coral): Remove feature flag topic-type-filter
  coral/src/app/features/topics/browse/BrowseTopics.test.tsx
  coral/src/app/features/topics/browse/BrowseTopics.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
Labels: Frontend

#2242 feat(coral): Add timeframe dropdown
  coral/src/app/features/dashboard/Dashboard.tsx
  coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
  coral/src/app/features/dashboard/hooks/useDashboardData.ts
  coral/src/domain/analytics/analytics-api.ts
Labels: enhancement, Frontend

#2236 feat(coral): remove feature flag dashboard
  coral/src/app/layout/main-navigation/MainNavigation.test.tsx
  coral/src/app/layout/main-navigation/MainNavigation.tsx
  coral/src/app/router.tsx
  coral/src/services/feature-flags/types.ts
  coral/vite.config.ts
  core/src/main/java/io/aiven/klaw/auth/KwAuthenticationSuccessHandler.java
  e2e/tests/basic-health-check.spec.ts
Labels: Frontend

#2237 refactor(core): Delete SAAS entities
  coral/src/services/api.ts
  coral/types/api.d.ts
  coral/vite.config.ts
  core/src/main/java/io/aiven/klaw/config/ConfigUtils.java
  core/src/main/java/io/aiven/klaw/constants/UriConstants.java
  core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
  core/src/main/java/io/aiven/klaw/controller/TemplateMapController.java
  core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
  core/src/main/java/io/aiven/klaw/error/KlawErrorMessages.java
  core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
  core/src/main/java/io/aiven/klaw/model/requests/RegisterSaasUserInfoModel.java
  core/src/main/java/io/aiven/klaw/model/response/AclCommands.java
  core/src/main/java/io/aiven/klaw/model/response/AuthenticationInfo.java
  core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
  core/src/main/java/io/aiven/klaw/service/DefaultDataService.java
  core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
  core/src/main/java/io/aiven/klaw/service/MailUtils.java
  core/src/main/java/io/aiven/klaw/service/RolesPermissionsControllerService.java
  core/src/main/java/io/aiven/klaw/service/SaasService.java
  core/src/main/java/io/aiven/klaw/service/UiControllerLoginService.java
  core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
  core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
  core/src/main/resources/application.properties
  core/src/main/resources/static/js/envs.js
  core/src/main/resources/static/js/loginSaas.js
  core/src/main/resources/static/js/manageUsers.js
  core/src/main/resources/static/js/oauthLogin.js
  core/src/main/resources/static/js/registerUsers.js
  core/src/main/resources/templates/addCluster.html
  core/src/main/resources/templates/addUser.html
  core/src/main/resources/templates/helpwizard.html
  core/src/main/resources/templates/loginSaas.html
  core/src/main/resources/templates/newADUser.html
  core/src/main/resources/templates/oauthLogin.html
  core/src/main/resources/templates/registerSaas.html
  core/src/main/resources/templates/registrationReviewSaas.html
  core/src/test/java/io/aiven/klaw/SsoActiveDirectoryAuthenticationIT.java
  core/src/test/java/io/aiven/klaw/service/UiControllerLoginServiceTest.java
  core/src/test/resources/test-application-rdbms-ad-authorization.properties
  core/src/test/resources/test-application-rdbms-sso-ad.properties
  core/src/test/resources/test-application-rdbms-windows-ad.properties
  core/src/test/resources/test-application-rdbms.properties
  core/src/test/resources/test-application-rdbms1.properties
  openapi.yaml
Labels: Housekeeping, Backend

#2251 feat(coral): Add permissions UI primitives
  coral/src/app/components/PermissionCheck.test.tsx
  coral/src/app/components/PermissionCheck.tsx
  coral/src/app/context-provider/AuthProvider.tsx
  coral/src/app/layout/header/ProfileDropdown.test.tsx
  coral/src/domain/auth-user/auth-user-api.ts
  coral/src/domain/auth-user/auth-user-test-helper.ts
  coral/src/domain/auth-user/auth-user-types.ts
  coral/src/services/feature-flags/route-utils.test.tsx
  coral/src/services/feature-flags/route-utils.tsx
Labels: enhancement, Frontend
